/**
 * RealmForge Authoritative Raid Boss Scaling & Co-op Difficulty Formulas
 * Dynamic health, damage, and enrage scaling based on active team size, ELO ratings, and survival time.
 */

export interface RaidScalingProfile {
  waveNumber: number;
  playerCount: number;
  hpMultiplier: number;
  damageMultiplier: number;
  armorRating: number;
  magicResistRating: number;
  enrageTimerSec: number;
}

export const RAID_SCALING_PROFILES: RaidScalingProfile[] = [
  {
    waveNumber: 1,
    playerCount: 1,
    hpMultiplier: 1.12,
    damageMultiplier: 1.08,
    armorRating: 15.8,
    magicResistRating: 12.75,
    enrageTimerSec: 119.5,
  },
  {
    waveNumber: 1,
    playerCount: 2,
    hpMultiplier: 1.87,
    damageMultiplier: 1.43,
    armorRating: 15.8,
    magicResistRating: 12.75,
    enrageTimerSec: 119.5,
  },
  {
    waveNumber: 1,
    playerCount: 3,
    hpMultiplier: 2.62,
    damageMultiplier: 1.78,
    armorRating: 15.8,
    magicResistRating: 12.75,
    enrageTimerSec: 119.5,
  },
  {
    waveNumber: 1,
    playerCount: 4,
    hpMultiplier: 3.37,
    damageMultiplier: 2.13,
    armorRating: 15.8,
    magicResistRating: 12.75,
    enrageTimerSec: 119.5,
  },
  {
    waveNumber: 2,
    playerCount: 1,
    hpMultiplier: 1.24,
    damageMultiplier: 1.16,
    armorRating: 16.6,
    magicResistRating: 13.5,
    enrageTimerSec: 119,
  },
  {
    waveNumber: 2,
    playerCount: 2,
    hpMultiplier: 1.99,
    damageMultiplier: 1.51,
    armorRating: 16.6,
    magicResistRating: 13.5,
    enrageTimerSec: 119,
  },
  {
    waveNumber: 2,
    playerCount: 3,
    hpMultiplier: 2.74,
    damageMultiplier: 1.86,
    armorRating: 16.6,
    magicResistRating: 13.5,
    enrageTimerSec: 119,
  },
  {
    waveNumber: 2,
    playerCount: 4,
    hpMultiplier: 3.49,
    damageMultiplier: 2.21,
    armorRating: 16.6,
    magicResistRating: 13.5,
    enrageTimerSec: 119,
  },
  {
    waveNumber: 3,
    playerCount: 1,
    hpMultiplier: 1.36,
    damageMultiplier: 1.24,
    armorRating: 17.4,
    magicResistRating: 14.25,
    enrageTimerSec: 118.5,
  },
  {
    waveNumber: 3,
    playerCount: 2,
    hpMultiplier: 2.11,
    damageMultiplier: 1.59,
    armorRating: 17.4,
    magicResistRating: 14.25,
    enrageTimerSec: 118.5,
  },
  {
    waveNumber: 3,
    playerCount: 3,
    hpMultiplier: 2.86,
    damageMultiplier: 1.94,
    armorRating: 17.4,
    magicResistRating: 14.25,
    enrageTimerSec: 118.5,
  },
  {
    waveNumber: 3,
    playerCount: 4,
    hpMultiplier: 3.61,
    damageMultiplier: 2.29,
    armorRating: 17.4,
    magicResistRating: 14.25,
    enrageTimerSec: 118.5,
  },
  {
    waveNumber: 4,
    playerCount: 1,
    hpMultiplier: 1.48,
    damageMultiplier: 1.32,
    armorRating: 18.2,
    magicResistRating: 15,
    enrageTimerSec: 118,
  },
  {
    waveNumber: 4,
    playerCount: 2,
    hpMultiplier: 2.23,
    damageMultiplier: 1.67,
    armorRating: 18.2,
    magicResistRating: 15,
    enrageTimerSec: 118,
  },
  {
    waveNumber: 4,
    playerCount: 3,
    hpMultiplier: 2.98,
    damageMultiplier: 2.02,
    armorRating: 18.2,
    magicResistRating: 15,
    enrageTimerSec: 118,
  },
  {
    waveNumber: 4,
    playerCount: 4,
    hpMultiplier: 3.73,
    damageMultiplier: 2.37,
    armorRating: 18.2,
    magicResistRating: 15,
    enrageTimerSec: 118,
  },
  {
    waveNumber: 5,
    playerCount: 1,
    hpMultiplier: 1.6,
    damageMultiplier: 1.4,
    armorRating: 19,
    magicResistRating: 15.75,
    enrageTimerSec: 117.5,
  },
  {
    waveNumber: 5,
    playerCount: 2,
    hpMultiplier: 2.35,
    damageMultiplier: 1.75,
    armorRating: 19,
    magicResistRating: 15.75,
    enrageTimerSec: 117.5,
  },
  {
    waveNumber: 5,
    playerCount: 3,
    hpMultiplier: 3.1,
    damageMultiplier: 2.1,
    armorRating: 19,
    magicResistRating: 15.75,
    enrageTimerSec: 117.5,
  },
  {
    waveNumber: 5,
    playerCount: 4,
    hpMultiplier: 3.85,
    damageMultiplier: 2.45,
    armorRating: 19,
    magicResistRating: 15.75,
    enrageTimerSec: 117.5,
  },
  {
    waveNumber: 6,
    playerCount: 1,
    hpMultiplier: 1.72,
    damageMultiplier: 1.48,
    armorRating: 19.8,
    magicResistRating: 16.5,
    enrageTimerSec: 117,
  },
  {
    waveNumber: 6,
    playerCount: 2,
    hpMultiplier: 2.47,
    damageMultiplier: 1.83,
    armorRating: 19.8,
    magicResistRating: 16.5,
    enrageTimerSec: 117,
  },
  {
    waveNumber: 6,
    playerCount: 3,
    hpMultiplier: 3.22,
    damageMultiplier: 2.18,
    armorRating: 19.8,
    magicResistRating: 16.5,
    enrageTimerSec: 117,
  },
  {
    waveNumber: 6,
    playerCount: 4,
    hpMultiplier: 3.97,
    damageMultiplier: 2.53,
    armorRating: 19.8,
    magicResistRating: 16.5,
    enrageTimerSec: 117,
  },
  {
    waveNumber: 7,
    playerCount: 1,
    hpMultiplier: 1.84,
    damageMultiplier: 1.56,
    armorRating: 20.6,
    magicResistRating: 17.25,
    enrageTimerSec: 116.5,
  },
  {
    waveNumber: 7,
    playerCount: 2,
    hpMultiplier: 2.59,
    damageMultiplier: 1.91,
    armorRating: 20.6,
    magicResistRating: 17.25,
    enrageTimerSec: 116.5,
  },
  {
    waveNumber: 7,
    playerCount: 3,
    hpMultiplier: 3.34,
    damageMultiplier: 2.26,
    armorRating: 20.6,
    magicResistRating: 17.25,
    enrageTimerSec: 116.5,
  },
  {
    waveNumber: 7,
    playerCount: 4,
    hpMultiplier: 4.09,
    damageMultiplier: 2.61,
    armorRating: 20.6,
    magicResistRating: 17.25,
    enrageTimerSec: 116.5,
  },
  {
    waveNumber: 8,
    playerCount: 1,
    hpMultiplier: 1.96,
    damageMultiplier: 1.64,
    armorRating: 21.4,
    magicResistRating: 18,
    enrageTimerSec: 116,
  },
  {
    waveNumber: 8,
    playerCount: 2,
    hpMultiplier: 2.71,
    damageMultiplier: 1.99,
    armorRating: 21.4,
    magicResistRating: 18,
    enrageTimerSec: 116,
  },
  {
    waveNumber: 8,
    playerCount: 3,
    hpMultiplier: 3.46,
    damageMultiplier: 2.34,
    armorRating: 21.4,
    magicResistRating: 18,
    enrageTimerSec: 116,
  },
  {
    waveNumber: 8,
    playerCount: 4,
    hpMultiplier: 4.21,
    damageMultiplier: 2.69,
    armorRating: 21.4,
    magicResistRating: 18,
    enrageTimerSec: 116,
  },
  {
    waveNumber: 9,
    playerCount: 1,
    hpMultiplier: 2.08,
    damageMultiplier: 1.72,
    armorRating: 22.2,
    magicResistRating: 18.75,
    enrageTimerSec: 115.5,
  },
  {
    waveNumber: 9,
    playerCount: 2,
    hpMultiplier: 2.83,
    damageMultiplier: 2.07,
    armorRating: 22.2,
    magicResistRating: 18.75,
    enrageTimerSec: 115.5,
  },
  {
    waveNumber: 9,
    playerCount: 3,
    hpMultiplier: 3.58,
    damageMultiplier: 2.42,
    armorRating: 22.2,
    magicResistRating: 18.75,
    enrageTimerSec: 115.5,
  },
  {
    waveNumber: 9,
    playerCount: 4,
    hpMultiplier: 4.33,
    damageMultiplier: 2.77,
    armorRating: 22.2,
    magicResistRating: 18.75,
    enrageTimerSec: 115.5,
  },
  {
    waveNumber: 10,
    playerCount: 1,
    hpMultiplier: 2.2,
    damageMultiplier: 1.8,
    armorRating: 23,
    magicResistRating: 19.5,
    enrageTimerSec: 115,
  },
  {
    waveNumber: 10,
    playerCount: 2,
    hpMultiplier: 2.95,
    damageMultiplier: 2.15,
    armorRating: 23,
    magicResistRating: 19.5,
    enrageTimerSec: 115,
  },
  {
    waveNumber: 10,
    playerCount: 3,
    hpMultiplier: 3.7,
    damageMultiplier: 2.5,
    armorRating: 23,
    magicResistRating: 19.5,
    enrageTimerSec: 115,
  },
  {
    waveNumber: 10,
    playerCount: 4,
    hpMultiplier: 4.45,
    damageMultiplier: 2.85,
    armorRating: 23,
    magicResistRating: 19.5,
    enrageTimerSec: 115,
  },
  {
    waveNumber: 11,
    playerCount: 1,
    hpMultiplier: 2.32,
    damageMultiplier: 1.88,
    armorRating: 23.8,
    magicResistRating: 20.25,
    enrageTimerSec: 114.5,
  },
  {
    waveNumber: 11,
    playerCount: 2,
    hpMultiplier: 3.07,
    damageMultiplier: 2.23,
    armorRating: 23.8,
    magicResistRating: 20.25,
    enrageTimerSec: 114.5,
  },
  {
    waveNumber: 11,
    playerCount: 3,
    hpMultiplier: 3.82,
    damageMultiplier: 2.58,
    armorRating: 23.8,
    magicResistRating: 20.25,
    enrageTimerSec: 114.5,
  },
  {
    waveNumber: 11,
    playerCount: 4,
    hpMultiplier: 4.57,
    damageMultiplier: 2.93,
    armorRating: 23.8,
    magicResistRating: 20.25,
    enrageTimerSec: 114.5,
  },
  {
    waveNumber: 12,
    playerCount: 1,
    hpMultiplier: 2.44,
    damageMultiplier: 1.96,
    armorRating: 24.6,
    magicResistRating: 21,
    enrageTimerSec: 114,
  },
  {
    waveNumber: 12,
    playerCount: 2,
    hpMultiplier: 3.19,
    damageMultiplier: 2.31,
    armorRating: 24.6,
    magicResistRating: 21,
    enrageTimerSec: 114,
  },
  {
    waveNumber: 12,
    playerCount: 3,
    hpMultiplier: 3.94,
    damageMultiplier: 2.66,
    armorRating: 24.6,
    magicResistRating: 21,
    enrageTimerSec: 114,
  },
  {
    waveNumber: 12,
    playerCount: 4,
    hpMultiplier: 4.69,
    damageMultiplier: 3.01,
    armorRating: 24.6,
    magicResistRating: 21,
    enrageTimerSec: 114,
  },
  {
    waveNumber: 13,
    playerCount: 1,
    hpMultiplier: 2.56,
    damageMultiplier: 2.04,
    armorRating: 25.4,
    magicResistRating: 21.75,
    enrageTimerSec: 113.5,
  },
  {
    waveNumber: 13,
    playerCount: 2,
    hpMultiplier: 3.31,
    damageMultiplier: 2.39,
    armorRating: 25.4,
    magicResistRating: 21.75,
    enrageTimerSec: 113.5,
  },
  {
    waveNumber: 13,
    playerCount: 3,
    hpMultiplier: 4.06,
    damageMultiplier: 2.74,
    armorRating: 25.4,
    magicResistRating: 21.75,
    enrageTimerSec: 113.5,
  },
  {
    waveNumber: 13,
    playerCount: 4,
    hpMultiplier: 4.81,
    damageMultiplier: 3.09,
    armorRating: 25.4,
    magicResistRating: 21.75,
    enrageTimerSec: 113.5,
  },
  {
    waveNumber: 14,
    playerCount: 1,
    hpMultiplier: 2.68,
    damageMultiplier: 2.12,
    armorRating: 26.200000000000003,
    magicResistRating: 22.5,
    enrageTimerSec: 113,
  },
  {
    waveNumber: 14,
    playerCount: 2,
    hpMultiplier: 3.43,
    damageMultiplier: 2.47,
    armorRating: 26.200000000000003,
    magicResistRating: 22.5,
    enrageTimerSec: 113,
  },
  {
    waveNumber: 14,
    playerCount: 3,
    hpMultiplier: 4.18,
    damageMultiplier: 2.82,
    armorRating: 26.200000000000003,
    magicResistRating: 22.5,
    enrageTimerSec: 113,
  },
  {
    waveNumber: 14,
    playerCount: 4,
    hpMultiplier: 4.93,
    damageMultiplier: 3.17,
    armorRating: 26.200000000000003,
    magicResistRating: 22.5,
    enrageTimerSec: 113,
  },
  {
    waveNumber: 15,
    playerCount: 1,
    hpMultiplier: 2.8,
    damageMultiplier: 2.2,
    armorRating: 27,
    magicResistRating: 23.25,
    enrageTimerSec: 112.5,
  },
  {
    waveNumber: 15,
    playerCount: 2,
    hpMultiplier: 3.55,
    damageMultiplier: 2.55,
    armorRating: 27,
    magicResistRating: 23.25,
    enrageTimerSec: 112.5,
  },
  {
    waveNumber: 15,
    playerCount: 3,
    hpMultiplier: 4.3,
    damageMultiplier: 2.9,
    armorRating: 27,
    magicResistRating: 23.25,
    enrageTimerSec: 112.5,
  },
  {
    waveNumber: 15,
    playerCount: 4,
    hpMultiplier: 5.05,
    damageMultiplier: 3.25,
    armorRating: 27,
    magicResistRating: 23.25,
    enrageTimerSec: 112.5,
  },
  {
    waveNumber: 16,
    playerCount: 1,
    hpMultiplier: 2.92,
    damageMultiplier: 2.28,
    armorRating: 27.8,
    magicResistRating: 24,
    enrageTimerSec: 112,
  },
  {
    waveNumber: 16,
    playerCount: 2,
    hpMultiplier: 3.67,
    damageMultiplier: 2.63,
    armorRating: 27.8,
    magicResistRating: 24,
    enrageTimerSec: 112,
  },
  {
    waveNumber: 16,
    playerCount: 3,
    hpMultiplier: 4.42,
    damageMultiplier: 2.98,
    armorRating: 27.8,
    magicResistRating: 24,
    enrageTimerSec: 112,
  },
  {
    waveNumber: 16,
    playerCount: 4,
    hpMultiplier: 5.17,
    damageMultiplier: 3.33,
    armorRating: 27.8,
    magicResistRating: 24,
    enrageTimerSec: 112,
  },
  {
    waveNumber: 17,
    playerCount: 1,
    hpMultiplier: 3.04,
    damageMultiplier: 2.36,
    armorRating: 28.6,
    magicResistRating: 24.75,
    enrageTimerSec: 111.5,
  },
  {
    waveNumber: 17,
    playerCount: 2,
    hpMultiplier: 3.79,
    damageMultiplier: 2.71,
    armorRating: 28.6,
    magicResistRating: 24.75,
    enrageTimerSec: 111.5,
  },
  {
    waveNumber: 17,
    playerCount: 3,
    hpMultiplier: 4.54,
    damageMultiplier: 3.06,
    armorRating: 28.6,
    magicResistRating: 24.75,
    enrageTimerSec: 111.5,
  },
  {
    waveNumber: 17,
    playerCount: 4,
    hpMultiplier: 5.29,
    damageMultiplier: 3.41,
    armorRating: 28.6,
    magicResistRating: 24.75,
    enrageTimerSec: 111.5,
  },
  {
    waveNumber: 18,
    playerCount: 1,
    hpMultiplier: 3.16,
    damageMultiplier: 2.44,
    armorRating: 29.4,
    magicResistRating: 25.5,
    enrageTimerSec: 111,
  },
  {
    waveNumber: 18,
    playerCount: 2,
    hpMultiplier: 3.91,
    damageMultiplier: 2.79,
    armorRating: 29.4,
    magicResistRating: 25.5,
    enrageTimerSec: 111,
  },
  {
    waveNumber: 18,
    playerCount: 3,
    hpMultiplier: 4.66,
    damageMultiplier: 3.14,
    armorRating: 29.4,
    magicResistRating: 25.5,
    enrageTimerSec: 111,
  },
  {
    waveNumber: 18,
    playerCount: 4,
    hpMultiplier: 5.41,
    damageMultiplier: 3.49,
    armorRating: 29.4,
    magicResistRating: 25.5,
    enrageTimerSec: 111,
  },
  {
    waveNumber: 19,
    playerCount: 1,
    hpMultiplier: 3.28,
    damageMultiplier: 2.52,
    armorRating: 30.200000000000003,
    magicResistRating: 26.25,
    enrageTimerSec: 110.5,
  },
  {
    waveNumber: 19,
    playerCount: 2,
    hpMultiplier: 4.03,
    damageMultiplier: 2.87,
    armorRating: 30.200000000000003,
    magicResistRating: 26.25,
    enrageTimerSec: 110.5,
  },
  {
    waveNumber: 19,
    playerCount: 3,
    hpMultiplier: 4.78,
    damageMultiplier: 3.22,
    armorRating: 30.200000000000003,
    magicResistRating: 26.25,
    enrageTimerSec: 110.5,
  },
  {
    waveNumber: 19,
    playerCount: 4,
    hpMultiplier: 5.53,
    damageMultiplier: 3.57,
    armorRating: 30.200000000000003,
    magicResistRating: 26.25,
    enrageTimerSec: 110.5,
  },
  {
    waveNumber: 20,
    playerCount: 1,
    hpMultiplier: 3.4,
    damageMultiplier: 2.6,
    armorRating: 31,
    magicResistRating: 27,
    enrageTimerSec: 110,
  },
  {
    waveNumber: 20,
    playerCount: 2,
    hpMultiplier: 4.15,
    damageMultiplier: 2.95,
    armorRating: 31,
    magicResistRating: 27,
    enrageTimerSec: 110,
  },
  {
    waveNumber: 20,
    playerCount: 3,
    hpMultiplier: 4.9,
    damageMultiplier: 3.3,
    armorRating: 31,
    magicResistRating: 27,
    enrageTimerSec: 110,
  },
  {
    waveNumber: 20,
    playerCount: 4,
    hpMultiplier: 5.65,
    damageMultiplier: 3.65,
    armorRating: 31,
    magicResistRating: 27,
    enrageTimerSec: 110,
  },
  {
    waveNumber: 21,
    playerCount: 1,
    hpMultiplier: 3.52,
    damageMultiplier: 2.68,
    armorRating: 31.8,
    magicResistRating: 27.75,
    enrageTimerSec: 109.5,
  },
  {
    waveNumber: 21,
    playerCount: 2,
    hpMultiplier: 4.27,
    damageMultiplier: 3.03,
    armorRating: 31.8,
    magicResistRating: 27.75,
    enrageTimerSec: 109.5,
  },
  {
    waveNumber: 21,
    playerCount: 3,
    hpMultiplier: 5.02,
    damageMultiplier: 3.38,
    armorRating: 31.8,
    magicResistRating: 27.75,
    enrageTimerSec: 109.5,
  },
  {
    waveNumber: 21,
    playerCount: 4,
    hpMultiplier: 5.77,
    damageMultiplier: 3.73,
    armorRating: 31.8,
    magicResistRating: 27.75,
    enrageTimerSec: 109.5,
  },
  {
    waveNumber: 22,
    playerCount: 1,
    hpMultiplier: 3.64,
    damageMultiplier: 2.76,
    armorRating: 32.6,
    magicResistRating: 28.5,
    enrageTimerSec: 109,
  },
  {
    waveNumber: 22,
    playerCount: 2,
    hpMultiplier: 4.39,
    damageMultiplier: 3.11,
    armorRating: 32.6,
    magicResistRating: 28.5,
    enrageTimerSec: 109,
  },
  {
    waveNumber: 22,
    playerCount: 3,
    hpMultiplier: 5.14,
    damageMultiplier: 3.46,
    armorRating: 32.6,
    magicResistRating: 28.5,
    enrageTimerSec: 109,
  },
  {
    waveNumber: 22,
    playerCount: 4,
    hpMultiplier: 5.89,
    damageMultiplier: 3.81,
    armorRating: 32.6,
    magicResistRating: 28.5,
    enrageTimerSec: 109,
  },
  {
    waveNumber: 23,
    playerCount: 1,
    hpMultiplier: 3.76,
    damageMultiplier: 2.84,
    armorRating: 33.400000000000006,
    magicResistRating: 29.25,
    enrageTimerSec: 108.5,
  },
  {
    waveNumber: 23,
    playerCount: 2,
    hpMultiplier: 4.51,
    damageMultiplier: 3.19,
    armorRating: 33.400000000000006,
    magicResistRating: 29.25,
    enrageTimerSec: 108.5,
  },
  {
    waveNumber: 23,
    playerCount: 3,
    hpMultiplier: 5.26,
    damageMultiplier: 3.54,
    armorRating: 33.400000000000006,
    magicResistRating: 29.25,
    enrageTimerSec: 108.5,
  },
  {
    waveNumber: 23,
    playerCount: 4,
    hpMultiplier: 6.01,
    damageMultiplier: 3.89,
    armorRating: 33.400000000000006,
    magicResistRating: 29.25,
    enrageTimerSec: 108.5,
  },
  {
    waveNumber: 24,
    playerCount: 1,
    hpMultiplier: 3.88,
    damageMultiplier: 2.92,
    armorRating: 34.2,
    magicResistRating: 30,
    enrageTimerSec: 108,
  },
  {
    waveNumber: 24,
    playerCount: 2,
    hpMultiplier: 4.63,
    damageMultiplier: 3.27,
    armorRating: 34.2,
    magicResistRating: 30,
    enrageTimerSec: 108,
  },
  {
    waveNumber: 24,
    playerCount: 3,
    hpMultiplier: 5.38,
    damageMultiplier: 3.62,
    armorRating: 34.2,
    magicResistRating: 30,
    enrageTimerSec: 108,
  },
  {
    waveNumber: 24,
    playerCount: 4,
    hpMultiplier: 6.13,
    damageMultiplier: 3.97,
    armorRating: 34.2,
    magicResistRating: 30,
    enrageTimerSec: 108,
  },
  {
    waveNumber: 25,
    playerCount: 1,
    hpMultiplier: 4,
    damageMultiplier: 3,
    armorRating: 35,
    magicResistRating: 30.75,
    enrageTimerSec: 107.5,
  },
  {
    waveNumber: 25,
    playerCount: 2,
    hpMultiplier: 4.75,
    damageMultiplier: 3.35,
    armorRating: 35,
    magicResistRating: 30.75,
    enrageTimerSec: 107.5,
  },
  {
    waveNumber: 25,
    playerCount: 3,
    hpMultiplier: 5.5,
    damageMultiplier: 3.7,
    armorRating: 35,
    magicResistRating: 30.75,
    enrageTimerSec: 107.5,
  },
  {
    waveNumber: 25,
    playerCount: 4,
    hpMultiplier: 6.25,
    damageMultiplier: 4.05,
    armorRating: 35,
    magicResistRating: 30.75,
    enrageTimerSec: 107.5,
  },
  {
    waveNumber: 26,
    playerCount: 1,
    hpMultiplier: 4.12,
    damageMultiplier: 3.08,
    armorRating: 35.8,
    magicResistRating: 31.5,
    enrageTimerSec: 107,
  },
  {
    waveNumber: 26,
    playerCount: 2,
    hpMultiplier: 4.87,
    damageMultiplier: 3.43,
    armorRating: 35.8,
    magicResistRating: 31.5,
    enrageTimerSec: 107,
  },
  {
    waveNumber: 26,
    playerCount: 3,
    hpMultiplier: 5.62,
    damageMultiplier: 3.78,
    armorRating: 35.8,
    magicResistRating: 31.5,
    enrageTimerSec: 107,
  },
  {
    waveNumber: 26,
    playerCount: 4,
    hpMultiplier: 6.37,
    damageMultiplier: 4.13,
    armorRating: 35.8,
    magicResistRating: 31.5,
    enrageTimerSec: 107,
  },
  {
    waveNumber: 27,
    playerCount: 1,
    hpMultiplier: 4.24,
    damageMultiplier: 3.16,
    armorRating: 36.6,
    magicResistRating: 32.25,
    enrageTimerSec: 106.5,
  },
  {
    waveNumber: 27,
    playerCount: 2,
    hpMultiplier: 4.99,
    damageMultiplier: 3.51,
    armorRating: 36.6,
    magicResistRating: 32.25,
    enrageTimerSec: 106.5,
  },
  {
    waveNumber: 27,
    playerCount: 3,
    hpMultiplier: 5.74,
    damageMultiplier: 3.86,
    armorRating: 36.6,
    magicResistRating: 32.25,
    enrageTimerSec: 106.5,
  },
  {
    waveNumber: 27,
    playerCount: 4,
    hpMultiplier: 6.49,
    damageMultiplier: 4.21,
    armorRating: 36.6,
    magicResistRating: 32.25,
    enrageTimerSec: 106.5,
  },
  {
    waveNumber: 28,
    playerCount: 1,
    hpMultiplier: 4.36,
    damageMultiplier: 3.24,
    armorRating: 37.400000000000006,
    magicResistRating: 33,
    enrageTimerSec: 106,
  },
  {
    waveNumber: 28,
    playerCount: 2,
    hpMultiplier: 5.11,
    damageMultiplier: 3.59,
    armorRating: 37.400000000000006,
    magicResistRating: 33,
    enrageTimerSec: 106,
  },
  {
    waveNumber: 28,
    playerCount: 3,
    hpMultiplier: 5.86,
    damageMultiplier: 3.94,
    armorRating: 37.400000000000006,
    magicResistRating: 33,
    enrageTimerSec: 106,
  },
  {
    waveNumber: 28,
    playerCount: 4,
    hpMultiplier: 6.61,
    damageMultiplier: 4.29,
    armorRating: 37.400000000000006,
    magicResistRating: 33,
    enrageTimerSec: 106,
  },
  {
    waveNumber: 29,
    playerCount: 1,
    hpMultiplier: 4.48,
    damageMultiplier: 3.32,
    armorRating: 38.2,
    magicResistRating: 33.75,
    enrageTimerSec: 105.5,
  },
  {
    waveNumber: 29,
    playerCount: 2,
    hpMultiplier: 5.23,
    damageMultiplier: 3.67,
    armorRating: 38.2,
    magicResistRating: 33.75,
    enrageTimerSec: 105.5,
  },
  {
    waveNumber: 29,
    playerCount: 3,
    hpMultiplier: 5.98,
    damageMultiplier: 4.02,
    armorRating: 38.2,
    magicResistRating: 33.75,
    enrageTimerSec: 105.5,
  },
  {
    waveNumber: 29,
    playerCount: 4,
    hpMultiplier: 6.73,
    damageMultiplier: 4.37,
    armorRating: 38.2,
    magicResistRating: 33.75,
    enrageTimerSec: 105.5,
  },
  {
    waveNumber: 30,
    playerCount: 1,
    hpMultiplier: 4.6,
    damageMultiplier: 3.4,
    armorRating: 39,
    magicResistRating: 34.5,
    enrageTimerSec: 105,
  },
  {
    waveNumber: 30,
    playerCount: 2,
    hpMultiplier: 5.35,
    damageMultiplier: 3.75,
    armorRating: 39,
    magicResistRating: 34.5,
    enrageTimerSec: 105,
  },
  {
    waveNumber: 30,
    playerCount: 3,
    hpMultiplier: 6.1,
    damageMultiplier: 4.1,
    armorRating: 39,
    magicResistRating: 34.5,
    enrageTimerSec: 105,
  },
  {
    waveNumber: 30,
    playerCount: 4,
    hpMultiplier: 6.85,
    damageMultiplier: 4.45,
    armorRating: 39,
    magicResistRating: 34.5,
    enrageTimerSec: 105,
  },
  {
    waveNumber: 31,
    playerCount: 1,
    hpMultiplier: 4.72,
    damageMultiplier: 3.48,
    armorRating: 39.8,
    magicResistRating: 35.25,
    enrageTimerSec: 104.5,
  },
  {
    waveNumber: 31,
    playerCount: 2,
    hpMultiplier: 5.47,
    damageMultiplier: 3.83,
    armorRating: 39.8,
    magicResistRating: 35.25,
    enrageTimerSec: 104.5,
  },
  {
    waveNumber: 31,
    playerCount: 3,
    hpMultiplier: 6.22,
    damageMultiplier: 4.18,
    armorRating: 39.8,
    magicResistRating: 35.25,
    enrageTimerSec: 104.5,
  },
  {
    waveNumber: 31,
    playerCount: 4,
    hpMultiplier: 6.97,
    damageMultiplier: 4.53,
    armorRating: 39.8,
    magicResistRating: 35.25,
    enrageTimerSec: 104.5,
  },
  {
    waveNumber: 32,
    playerCount: 1,
    hpMultiplier: 4.84,
    damageMultiplier: 3.56,
    armorRating: 40.6,
    magicResistRating: 36,
    enrageTimerSec: 104,
  },
  {
    waveNumber: 32,
    playerCount: 2,
    hpMultiplier: 5.59,
    damageMultiplier: 3.91,
    armorRating: 40.6,
    magicResistRating: 36,
    enrageTimerSec: 104,
  },
  {
    waveNumber: 32,
    playerCount: 3,
    hpMultiplier: 6.34,
    damageMultiplier: 4.26,
    armorRating: 40.6,
    magicResistRating: 36,
    enrageTimerSec: 104,
  },
  {
    waveNumber: 32,
    playerCount: 4,
    hpMultiplier: 7.09,
    damageMultiplier: 4.61,
    armorRating: 40.6,
    magicResistRating: 36,
    enrageTimerSec: 104,
  },
  {
    waveNumber: 33,
    playerCount: 1,
    hpMultiplier: 4.96,
    damageMultiplier: 3.64,
    armorRating: 41.400000000000006,
    magicResistRating: 36.75,
    enrageTimerSec: 103.5,
  },
  {
    waveNumber: 33,
    playerCount: 2,
    hpMultiplier: 5.71,
    damageMultiplier: 3.99,
    armorRating: 41.400000000000006,
    magicResistRating: 36.75,
    enrageTimerSec: 103.5,
  },
  {
    waveNumber: 33,
    playerCount: 3,
    hpMultiplier: 6.46,
    damageMultiplier: 4.34,
    armorRating: 41.400000000000006,
    magicResistRating: 36.75,
    enrageTimerSec: 103.5,
  },
  {
    waveNumber: 33,
    playerCount: 4,
    hpMultiplier: 7.21,
    damageMultiplier: 4.69,
    armorRating: 41.400000000000006,
    magicResistRating: 36.75,
    enrageTimerSec: 103.5,
  },
  {
    waveNumber: 34,
    playerCount: 1,
    hpMultiplier: 5.08,
    damageMultiplier: 3.72,
    armorRating: 42.2,
    magicResistRating: 37.5,
    enrageTimerSec: 103,
  },
  {
    waveNumber: 34,
    playerCount: 2,
    hpMultiplier: 5.83,
    damageMultiplier: 4.07,
    armorRating: 42.2,
    magicResistRating: 37.5,
    enrageTimerSec: 103,
  },
  {
    waveNumber: 34,
    playerCount: 3,
    hpMultiplier: 6.58,
    damageMultiplier: 4.42,
    armorRating: 42.2,
    magicResistRating: 37.5,
    enrageTimerSec: 103,
  },
  {
    waveNumber: 34,
    playerCount: 4,
    hpMultiplier: 7.33,
    damageMultiplier: 4.77,
    armorRating: 42.2,
    magicResistRating: 37.5,
    enrageTimerSec: 103,
  },
  {
    waveNumber: 35,
    playerCount: 1,
    hpMultiplier: 5.2,
    damageMultiplier: 3.8,
    armorRating: 43,
    magicResistRating: 38.25,
    enrageTimerSec: 102.5,
  },
  {
    waveNumber: 35,
    playerCount: 2,
    hpMultiplier: 5.95,
    damageMultiplier: 4.15,
    armorRating: 43,
    magicResistRating: 38.25,
    enrageTimerSec: 102.5,
  },
  {
    waveNumber: 35,
    playerCount: 3,
    hpMultiplier: 6.7,
    damageMultiplier: 4.5,
    armorRating: 43,
    magicResistRating: 38.25,
    enrageTimerSec: 102.5,
  },
  {
    waveNumber: 35,
    playerCount: 4,
    hpMultiplier: 7.45,
    damageMultiplier: 4.85,
    armorRating: 43,
    magicResistRating: 38.25,
    enrageTimerSec: 102.5,
  },
  {
    waveNumber: 36,
    playerCount: 1,
    hpMultiplier: 5.32,
    damageMultiplier: 3.88,
    armorRating: 43.8,
    magicResistRating: 39,
    enrageTimerSec: 102,
  },
  {
    waveNumber: 36,
    playerCount: 2,
    hpMultiplier: 6.07,
    damageMultiplier: 4.23,
    armorRating: 43.8,
    magicResistRating: 39,
    enrageTimerSec: 102,
  },
  {
    waveNumber: 36,
    playerCount: 3,
    hpMultiplier: 6.82,
    damageMultiplier: 4.58,
    armorRating: 43.8,
    magicResistRating: 39,
    enrageTimerSec: 102,
  },
  {
    waveNumber: 36,
    playerCount: 4,
    hpMultiplier: 7.57,
    damageMultiplier: 4.93,
    armorRating: 43.8,
    magicResistRating: 39,
    enrageTimerSec: 102,
  },
  {
    waveNumber: 37,
    playerCount: 1,
    hpMultiplier: 5.44,
    damageMultiplier: 3.96,
    armorRating: 44.6,
    magicResistRating: 39.75,
    enrageTimerSec: 101.5,
  },
  {
    waveNumber: 37,
    playerCount: 2,
    hpMultiplier: 6.19,
    damageMultiplier: 4.31,
    armorRating: 44.6,
    magicResistRating: 39.75,
    enrageTimerSec: 101.5,
  },
  {
    waveNumber: 37,
    playerCount: 3,
    hpMultiplier: 6.94,
    damageMultiplier: 4.66,
    armorRating: 44.6,
    magicResistRating: 39.75,
    enrageTimerSec: 101.5,
  },
  {
    waveNumber: 37,
    playerCount: 4,
    hpMultiplier: 7.69,
    damageMultiplier: 5.01,
    armorRating: 44.6,
    magicResistRating: 39.75,
    enrageTimerSec: 101.5,
  },
  {
    waveNumber: 38,
    playerCount: 1,
    hpMultiplier: 5.56,
    damageMultiplier: 4.04,
    armorRating: 45.400000000000006,
    magicResistRating: 40.5,
    enrageTimerSec: 101,
  },
  {
    waveNumber: 38,
    playerCount: 2,
    hpMultiplier: 6.31,
    damageMultiplier: 4.39,
    armorRating: 45.400000000000006,
    magicResistRating: 40.5,
    enrageTimerSec: 101,
  },
  {
    waveNumber: 38,
    playerCount: 3,
    hpMultiplier: 7.06,
    damageMultiplier: 4.74,
    armorRating: 45.400000000000006,
    magicResistRating: 40.5,
    enrageTimerSec: 101,
  },
  {
    waveNumber: 38,
    playerCount: 4,
    hpMultiplier: 7.81,
    damageMultiplier: 5.09,
    armorRating: 45.400000000000006,
    magicResistRating: 40.5,
    enrageTimerSec: 101,
  },
  {
    waveNumber: 39,
    playerCount: 1,
    hpMultiplier: 5.68,
    damageMultiplier: 4.12,
    armorRating: 46.2,
    magicResistRating: 41.25,
    enrageTimerSec: 100.5,
  },
  {
    waveNumber: 39,
    playerCount: 2,
    hpMultiplier: 6.43,
    damageMultiplier: 4.47,
    armorRating: 46.2,
    magicResistRating: 41.25,
    enrageTimerSec: 100.5,
  },
  {
    waveNumber: 39,
    playerCount: 3,
    hpMultiplier: 7.18,
    damageMultiplier: 4.82,
    armorRating: 46.2,
    magicResistRating: 41.25,
    enrageTimerSec: 100.5,
  },
  {
    waveNumber: 39,
    playerCount: 4,
    hpMultiplier: 7.93,
    damageMultiplier: 5.17,
    armorRating: 46.2,
    magicResistRating: 41.25,
    enrageTimerSec: 100.5,
  },
  {
    waveNumber: 40,
    playerCount: 1,
    hpMultiplier: 5.8,
    damageMultiplier: 4.2,
    armorRating: 47,
    magicResistRating: 42,
    enrageTimerSec: 100,
  },
  {
    waveNumber: 40,
    playerCount: 2,
    hpMultiplier: 6.55,
    damageMultiplier: 4.55,
    armorRating: 47,
    magicResistRating: 42,
    enrageTimerSec: 100,
  },
  {
    waveNumber: 40,
    playerCount: 3,
    hpMultiplier: 7.3,
    damageMultiplier: 4.9,
    armorRating: 47,
    magicResistRating: 42,
    enrageTimerSec: 100,
  },
  {
    waveNumber: 40,
    playerCount: 4,
    hpMultiplier: 8.05,
    damageMultiplier: 5.25,
    armorRating: 47,
    magicResistRating: 42,
    enrageTimerSec: 100,
  },
  {
    waveNumber: 41,
    playerCount: 1,
    hpMultiplier: 5.92,
    damageMultiplier: 4.28,
    armorRating: 47.800000000000004,
    magicResistRating: 42.75,
    enrageTimerSec: 99.5,
  },
  {
    waveNumber: 41,
    playerCount: 2,
    hpMultiplier: 6.67,
    damageMultiplier: 4.63,
    armorRating: 47.800000000000004,
    magicResistRating: 42.75,
    enrageTimerSec: 99.5,
  },
  {
    waveNumber: 41,
    playerCount: 3,
    hpMultiplier: 7.42,
    damageMultiplier: 4.98,
    armorRating: 47.800000000000004,
    magicResistRating: 42.75,
    enrageTimerSec: 99.5,
  },
  {
    waveNumber: 41,
    playerCount: 4,
    hpMultiplier: 8.17,
    damageMultiplier: 5.33,
    armorRating: 47.800000000000004,
    magicResistRating: 42.75,
    enrageTimerSec: 99.5,
  },
  {
    waveNumber: 42,
    playerCount: 1,
    hpMultiplier: 6.04,
    damageMultiplier: 4.36,
    armorRating: 48.6,
    magicResistRating: 43.5,
    enrageTimerSec: 99,
  },
  {
    waveNumber: 42,
    playerCount: 2,
    hpMultiplier: 6.79,
    damageMultiplier: 4.71,
    armorRating: 48.6,
    magicResistRating: 43.5,
    enrageTimerSec: 99,
  },
  {
    waveNumber: 42,
    playerCount: 3,
    hpMultiplier: 7.54,
    damageMultiplier: 5.06,
    armorRating: 48.6,
    magicResistRating: 43.5,
    enrageTimerSec: 99,
  },
  {
    waveNumber: 42,
    playerCount: 4,
    hpMultiplier: 8.29,
    damageMultiplier: 5.41,
    armorRating: 48.6,
    magicResistRating: 43.5,
    enrageTimerSec: 99,
  },
  {
    waveNumber: 43,
    playerCount: 1,
    hpMultiplier: 6.16,
    damageMultiplier: 4.44,
    armorRating: 49.4,
    magicResistRating: 44.25,
    enrageTimerSec: 98.5,
  },
  {
    waveNumber: 43,
    playerCount: 2,
    hpMultiplier: 6.91,
    damageMultiplier: 4.79,
    armorRating: 49.4,
    magicResistRating: 44.25,
    enrageTimerSec: 98.5,
  },
  {
    waveNumber: 43,
    playerCount: 3,
    hpMultiplier: 7.66,
    damageMultiplier: 5.14,
    armorRating: 49.4,
    magicResistRating: 44.25,
    enrageTimerSec: 98.5,
  },
  {
    waveNumber: 43,
    playerCount: 4,
    hpMultiplier: 8.41,
    damageMultiplier: 5.49,
    armorRating: 49.4,
    magicResistRating: 44.25,
    enrageTimerSec: 98.5,
  },
  {
    waveNumber: 44,
    playerCount: 1,
    hpMultiplier: 6.28,
    damageMultiplier: 4.52,
    armorRating: 50.2,
    magicResistRating: 45,
    enrageTimerSec: 98,
  },
  {
    waveNumber: 44,
    playerCount: 2,
    hpMultiplier: 7.03,
    damageMultiplier: 4.87,
    armorRating: 50.2,
    magicResistRating: 45,
    enrageTimerSec: 98,
  },
  {
    waveNumber: 44,
    playerCount: 3,
    hpMultiplier: 7.78,
    damageMultiplier: 5.22,
    armorRating: 50.2,
    magicResistRating: 45,
    enrageTimerSec: 98,
  },
  {
    waveNumber: 44,
    playerCount: 4,
    hpMultiplier: 8.53,
    damageMultiplier: 5.57,
    armorRating: 50.2,
    magicResistRating: 45,
    enrageTimerSec: 98,
  },
  {
    waveNumber: 45,
    playerCount: 1,
    hpMultiplier: 6.4,
    damageMultiplier: 4.6,
    armorRating: 51,
    magicResistRating: 45.75,
    enrageTimerSec: 97.5,
  },
  {
    waveNumber: 45,
    playerCount: 2,
    hpMultiplier: 7.15,
    damageMultiplier: 4.95,
    armorRating: 51,
    magicResistRating: 45.75,
    enrageTimerSec: 97.5,
  },
  {
    waveNumber: 45,
    playerCount: 3,
    hpMultiplier: 7.9,
    damageMultiplier: 5.3,
    armorRating: 51,
    magicResistRating: 45.75,
    enrageTimerSec: 97.5,
  },
  {
    waveNumber: 45,
    playerCount: 4,
    hpMultiplier: 8.65,
    damageMultiplier: 5.65,
    armorRating: 51,
    magicResistRating: 45.75,
    enrageTimerSec: 97.5,
  },
  {
    waveNumber: 46,
    playerCount: 1,
    hpMultiplier: 6.52,
    damageMultiplier: 4.68,
    armorRating: 51.800000000000004,
    magicResistRating: 46.5,
    enrageTimerSec: 97,
  },
  {
    waveNumber: 46,
    playerCount: 2,
    hpMultiplier: 7.27,
    damageMultiplier: 5.03,
    armorRating: 51.800000000000004,
    magicResistRating: 46.5,
    enrageTimerSec: 97,
  },
  {
    waveNumber: 46,
    playerCount: 3,
    hpMultiplier: 8.02,
    damageMultiplier: 5.38,
    armorRating: 51.800000000000004,
    magicResistRating: 46.5,
    enrageTimerSec: 97,
  },
  {
    waveNumber: 46,
    playerCount: 4,
    hpMultiplier: 8.77,
    damageMultiplier: 5.73,
    armorRating: 51.800000000000004,
    magicResistRating: 46.5,
    enrageTimerSec: 97,
  },
  {
    waveNumber: 47,
    playerCount: 1,
    hpMultiplier: 6.64,
    damageMultiplier: 4.76,
    armorRating: 52.6,
    magicResistRating: 47.25,
    enrageTimerSec: 96.5,
  },
  {
    waveNumber: 47,
    playerCount: 2,
    hpMultiplier: 7.39,
    damageMultiplier: 5.11,
    armorRating: 52.6,
    magicResistRating: 47.25,
    enrageTimerSec: 96.5,
  },
  {
    waveNumber: 47,
    playerCount: 3,
    hpMultiplier: 8.14,
    damageMultiplier: 5.46,
    armorRating: 52.6,
    magicResistRating: 47.25,
    enrageTimerSec: 96.5,
  },
  {
    waveNumber: 47,
    playerCount: 4,
    hpMultiplier: 8.89,
    damageMultiplier: 5.81,
    armorRating: 52.6,
    magicResistRating: 47.25,
    enrageTimerSec: 96.5,
  },
  {
    waveNumber: 48,
    playerCount: 1,
    hpMultiplier: 6.76,
    damageMultiplier: 4.84,
    armorRating: 53.400000000000006,
    magicResistRating: 48,
    enrageTimerSec: 96,
  },
  {
    waveNumber: 48,
    playerCount: 2,
    hpMultiplier: 7.51,
    damageMultiplier: 5.19,
    armorRating: 53.400000000000006,
    magicResistRating: 48,
    enrageTimerSec: 96,
  },
  {
    waveNumber: 48,
    playerCount: 3,
    hpMultiplier: 8.26,
    damageMultiplier: 5.54,
    armorRating: 53.400000000000006,
    magicResistRating: 48,
    enrageTimerSec: 96,
  },
  {
    waveNumber: 48,
    playerCount: 4,
    hpMultiplier: 9.01,
    damageMultiplier: 5.89,
    armorRating: 53.400000000000006,
    magicResistRating: 48,
    enrageTimerSec: 96,
  },
  {
    waveNumber: 49,
    playerCount: 1,
    hpMultiplier: 6.88,
    damageMultiplier: 4.92,
    armorRating: 54.2,
    magicResistRating: 48.75,
    enrageTimerSec: 95.5,
  },
  {
    waveNumber: 49,
    playerCount: 2,
    hpMultiplier: 7.63,
    damageMultiplier: 5.27,
    armorRating: 54.2,
    magicResistRating: 48.75,
    enrageTimerSec: 95.5,
  },
  {
    waveNumber: 49,
    playerCount: 3,
    hpMultiplier: 8.38,
    damageMultiplier: 5.62,
    armorRating: 54.2,
    magicResistRating: 48.75,
    enrageTimerSec: 95.5,
  },
  {
    waveNumber: 49,
    playerCount: 4,
    hpMultiplier: 9.13,
    damageMultiplier: 5.97,
    armorRating: 54.2,
    magicResistRating: 48.75,
    enrageTimerSec: 95.5,
  },
  {
    waveNumber: 50,
    playerCount: 1,
    hpMultiplier: 7,
    damageMultiplier: 5,
    armorRating: 55,
    magicResistRating: 49.5,
    enrageTimerSec: 95,
  },
  {
    waveNumber: 50,
    playerCount: 2,
    hpMultiplier: 7.75,
    damageMultiplier: 5.35,
    armorRating: 55,
    magicResistRating: 49.5,
    enrageTimerSec: 95,
  },
  {
    waveNumber: 50,
    playerCount: 3,
    hpMultiplier: 8.5,
    damageMultiplier: 5.7,
    armorRating: 55,
    magicResistRating: 49.5,
    enrageTimerSec: 95,
  },
  {
    waveNumber: 50,
    playerCount: 4,
    hpMultiplier: 9.25,
    damageMultiplier: 6.05,
    armorRating: 55,
    magicResistRating: 49.5,
    enrageTimerSec: 95,
  },
  {
    waveNumber: 51,
    playerCount: 1,
    hpMultiplier: 7.12,
    damageMultiplier: 5.08,
    armorRating: 55.800000000000004,
    magicResistRating: 50.25,
    enrageTimerSec: 94.5,
  },
  {
    waveNumber: 51,
    playerCount: 2,
    hpMultiplier: 7.87,
    damageMultiplier: 5.43,
    armorRating: 55.800000000000004,
    magicResistRating: 50.25,
    enrageTimerSec: 94.5,
  },
  {
    waveNumber: 51,
    playerCount: 3,
    hpMultiplier: 8.62,
    damageMultiplier: 5.78,
    armorRating: 55.800000000000004,
    magicResistRating: 50.25,
    enrageTimerSec: 94.5,
  },
  {
    waveNumber: 51,
    playerCount: 4,
    hpMultiplier: 9.37,
    damageMultiplier: 6.13,
    armorRating: 55.800000000000004,
    magicResistRating: 50.25,
    enrageTimerSec: 94.5,
  },
  {
    waveNumber: 52,
    playerCount: 1,
    hpMultiplier: 7.24,
    damageMultiplier: 5.16,
    armorRating: 56.6,
    magicResistRating: 51,
    enrageTimerSec: 94,
  },
  {
    waveNumber: 52,
    playerCount: 2,
    hpMultiplier: 7.99,
    damageMultiplier: 5.51,
    armorRating: 56.6,
    magicResistRating: 51,
    enrageTimerSec: 94,
  },
  {
    waveNumber: 52,
    playerCount: 3,
    hpMultiplier: 8.74,
    damageMultiplier: 5.86,
    armorRating: 56.6,
    magicResistRating: 51,
    enrageTimerSec: 94,
  },
  {
    waveNumber: 52,
    playerCount: 4,
    hpMultiplier: 9.49,
    damageMultiplier: 6.21,
    armorRating: 56.6,
    magicResistRating: 51,
    enrageTimerSec: 94,
  },
  {
    waveNumber: 53,
    playerCount: 1,
    hpMultiplier: 7.36,
    damageMultiplier: 5.24,
    armorRating: 57.400000000000006,
    magicResistRating: 51.75,
    enrageTimerSec: 93.5,
  },
  {
    waveNumber: 53,
    playerCount: 2,
    hpMultiplier: 8.11,
    damageMultiplier: 5.59,
    armorRating: 57.400000000000006,
    magicResistRating: 51.75,
    enrageTimerSec: 93.5,
  },
  {
    waveNumber: 53,
    playerCount: 3,
    hpMultiplier: 8.86,
    damageMultiplier: 5.94,
    armorRating: 57.400000000000006,
    magicResistRating: 51.75,
    enrageTimerSec: 93.5,
  },
  {
    waveNumber: 53,
    playerCount: 4,
    hpMultiplier: 9.61,
    damageMultiplier: 6.29,
    armorRating: 57.400000000000006,
    magicResistRating: 51.75,
    enrageTimerSec: 93.5,
  },
  {
    waveNumber: 54,
    playerCount: 1,
    hpMultiplier: 7.48,
    damageMultiplier: 5.32,
    armorRating: 58.2,
    magicResistRating: 52.5,
    enrageTimerSec: 93,
  },
  {
    waveNumber: 54,
    playerCount: 2,
    hpMultiplier: 8.23,
    damageMultiplier: 5.67,
    armorRating: 58.2,
    magicResistRating: 52.5,
    enrageTimerSec: 93,
  },
  {
    waveNumber: 54,
    playerCount: 3,
    hpMultiplier: 8.98,
    damageMultiplier: 6.02,
    armorRating: 58.2,
    magicResistRating: 52.5,
    enrageTimerSec: 93,
  },
  {
    waveNumber: 54,
    playerCount: 4,
    hpMultiplier: 9.73,
    damageMultiplier: 6.37,
    armorRating: 58.2,
    magicResistRating: 52.5,
    enrageTimerSec: 93,
  },
  {
    waveNumber: 55,
    playerCount: 1,
    hpMultiplier: 7.6,
    damageMultiplier: 5.4,
    armorRating: 59,
    magicResistRating: 53.25,
    enrageTimerSec: 92.5,
  },
  {
    waveNumber: 55,
    playerCount: 2,
    hpMultiplier: 8.35,
    damageMultiplier: 5.75,
    armorRating: 59,
    magicResistRating: 53.25,
    enrageTimerSec: 92.5,
  },
  {
    waveNumber: 55,
    playerCount: 3,
    hpMultiplier: 9.1,
    damageMultiplier: 6.1,
    armorRating: 59,
    magicResistRating: 53.25,
    enrageTimerSec: 92.5,
  },
  {
    waveNumber: 55,
    playerCount: 4,
    hpMultiplier: 9.85,
    damageMultiplier: 6.45,
    armorRating: 59,
    magicResistRating: 53.25,
    enrageTimerSec: 92.5,
  },
  {
    waveNumber: 56,
    playerCount: 1,
    hpMultiplier: 7.72,
    damageMultiplier: 5.48,
    armorRating: 59.800000000000004,
    magicResistRating: 54,
    enrageTimerSec: 92,
  },
  {
    waveNumber: 56,
    playerCount: 2,
    hpMultiplier: 8.47,
    damageMultiplier: 5.83,
    armorRating: 59.800000000000004,
    magicResistRating: 54,
    enrageTimerSec: 92,
  },
  {
    waveNumber: 56,
    playerCount: 3,
    hpMultiplier: 9.22,
    damageMultiplier: 6.18,
    armorRating: 59.800000000000004,
    magicResistRating: 54,
    enrageTimerSec: 92,
  },
  {
    waveNumber: 56,
    playerCount: 4,
    hpMultiplier: 9.97,
    damageMultiplier: 6.53,
    armorRating: 59.800000000000004,
    magicResistRating: 54,
    enrageTimerSec: 92,
  },
  {
    waveNumber: 57,
    playerCount: 1,
    hpMultiplier: 7.84,
    damageMultiplier: 5.56,
    armorRating: 60.6,
    magicResistRating: 54.75,
    enrageTimerSec: 91.5,
  },
  {
    waveNumber: 57,
    playerCount: 2,
    hpMultiplier: 8.59,
    damageMultiplier: 5.91,
    armorRating: 60.6,
    magicResistRating: 54.75,
    enrageTimerSec: 91.5,
  },
  {
    waveNumber: 57,
    playerCount: 3,
    hpMultiplier: 9.34,
    damageMultiplier: 6.26,
    armorRating: 60.6,
    magicResistRating: 54.75,
    enrageTimerSec: 91.5,
  },
  {
    waveNumber: 57,
    playerCount: 4,
    hpMultiplier: 10.09,
    damageMultiplier: 6.61,
    armorRating: 60.6,
    magicResistRating: 54.75,
    enrageTimerSec: 91.5,
  },
  {
    waveNumber: 58,
    playerCount: 1,
    hpMultiplier: 7.96,
    damageMultiplier: 5.64,
    armorRating: 61.400000000000006,
    magicResistRating: 55.5,
    enrageTimerSec: 91,
  },
  {
    waveNumber: 58,
    playerCount: 2,
    hpMultiplier: 8.71,
    damageMultiplier: 5.99,
    armorRating: 61.400000000000006,
    magicResistRating: 55.5,
    enrageTimerSec: 91,
  },
  {
    waveNumber: 58,
    playerCount: 3,
    hpMultiplier: 9.46,
    damageMultiplier: 6.34,
    armorRating: 61.400000000000006,
    magicResistRating: 55.5,
    enrageTimerSec: 91,
  },
  {
    waveNumber: 58,
    playerCount: 4,
    hpMultiplier: 10.21,
    damageMultiplier: 6.69,
    armorRating: 61.400000000000006,
    magicResistRating: 55.5,
    enrageTimerSec: 91,
  },
  {
    waveNumber: 59,
    playerCount: 1,
    hpMultiplier: 8.08,
    damageMultiplier: 5.72,
    armorRating: 62.2,
    magicResistRating: 56.25,
    enrageTimerSec: 90.5,
  },
  {
    waveNumber: 59,
    playerCount: 2,
    hpMultiplier: 8.83,
    damageMultiplier: 6.07,
    armorRating: 62.2,
    magicResistRating: 56.25,
    enrageTimerSec: 90.5,
  },
  {
    waveNumber: 59,
    playerCount: 3,
    hpMultiplier: 9.58,
    damageMultiplier: 6.42,
    armorRating: 62.2,
    magicResistRating: 56.25,
    enrageTimerSec: 90.5,
  },
  {
    waveNumber: 59,
    playerCount: 4,
    hpMultiplier: 10.33,
    damageMultiplier: 6.77,
    armorRating: 62.2,
    magicResistRating: 56.25,
    enrageTimerSec: 90.5,
  },
  {
    waveNumber: 60,
    playerCount: 1,
    hpMultiplier: 8.2,
    damageMultiplier: 5.8,
    armorRating: 63,
    magicResistRating: 57,
    enrageTimerSec: 90,
  },
  {
    waveNumber: 60,
    playerCount: 2,
    hpMultiplier: 8.95,
    damageMultiplier: 6.15,
    armorRating: 63,
    magicResistRating: 57,
    enrageTimerSec: 90,
  },
  {
    waveNumber: 60,
    playerCount: 3,
    hpMultiplier: 9.7,
    damageMultiplier: 6.5,
    armorRating: 63,
    magicResistRating: 57,
    enrageTimerSec: 90,
  },
  {
    waveNumber: 60,
    playerCount: 4,
    hpMultiplier: 10.45,
    damageMultiplier: 6.85,
    armorRating: 63,
    magicResistRating: 57,
    enrageTimerSec: 90,
  },
  {
    waveNumber: 61,
    playerCount: 1,
    hpMultiplier: 8.32,
    damageMultiplier: 5.88,
    armorRating: 63.800000000000004,
    magicResistRating: 57.75,
    enrageTimerSec: 89.5,
  },
  {
    waveNumber: 61,
    playerCount: 2,
    hpMultiplier: 9.07,
    damageMultiplier: 6.23,
    armorRating: 63.800000000000004,
    magicResistRating: 57.75,
    enrageTimerSec: 89.5,
  },
  {
    waveNumber: 61,
    playerCount: 3,
    hpMultiplier: 9.82,
    damageMultiplier: 6.58,
    armorRating: 63.800000000000004,
    magicResistRating: 57.75,
    enrageTimerSec: 89.5,
  },
  {
    waveNumber: 61,
    playerCount: 4,
    hpMultiplier: 10.57,
    damageMultiplier: 6.93,
    armorRating: 63.800000000000004,
    magicResistRating: 57.75,
    enrageTimerSec: 89.5,
  },
  {
    waveNumber: 62,
    playerCount: 1,
    hpMultiplier: 8.44,
    damageMultiplier: 5.96,
    armorRating: 64.6,
    magicResistRating: 58.5,
    enrageTimerSec: 89,
  },
  {
    waveNumber: 62,
    playerCount: 2,
    hpMultiplier: 9.19,
    damageMultiplier: 6.31,
    armorRating: 64.6,
    magicResistRating: 58.5,
    enrageTimerSec: 89,
  },
  {
    waveNumber: 62,
    playerCount: 3,
    hpMultiplier: 9.94,
    damageMultiplier: 6.66,
    armorRating: 64.6,
    magicResistRating: 58.5,
    enrageTimerSec: 89,
  },
  {
    waveNumber: 62,
    playerCount: 4,
    hpMultiplier: 10.69,
    damageMultiplier: 7.01,
    armorRating: 64.6,
    magicResistRating: 58.5,
    enrageTimerSec: 89,
  },
  {
    waveNumber: 63,
    playerCount: 1,
    hpMultiplier: 8.56,
    damageMultiplier: 6.04,
    armorRating: 65.4,
    magicResistRating: 59.25,
    enrageTimerSec: 88.5,
  },
  {
    waveNumber: 63,
    playerCount: 2,
    hpMultiplier: 9.31,
    damageMultiplier: 6.39,
    armorRating: 65.4,
    magicResistRating: 59.25,
    enrageTimerSec: 88.5,
  },
  {
    waveNumber: 63,
    playerCount: 3,
    hpMultiplier: 10.06,
    damageMultiplier: 6.74,
    armorRating: 65.4,
    magicResistRating: 59.25,
    enrageTimerSec: 88.5,
  },
  {
    waveNumber: 63,
    playerCount: 4,
    hpMultiplier: 10.81,
    damageMultiplier: 7.09,
    armorRating: 65.4,
    magicResistRating: 59.25,
    enrageTimerSec: 88.5,
  },
  {
    waveNumber: 64,
    playerCount: 1,
    hpMultiplier: 8.68,
    damageMultiplier: 6.12,
    armorRating: 66.2,
    magicResistRating: 60,
    enrageTimerSec: 88,
  },
  {
    waveNumber: 64,
    playerCount: 2,
    hpMultiplier: 9.43,
    damageMultiplier: 6.47,
    armorRating: 66.2,
    magicResistRating: 60,
    enrageTimerSec: 88,
  },
  {
    waveNumber: 64,
    playerCount: 3,
    hpMultiplier: 10.18,
    damageMultiplier: 6.82,
    armorRating: 66.2,
    magicResistRating: 60,
    enrageTimerSec: 88,
  },
  {
    waveNumber: 64,
    playerCount: 4,
    hpMultiplier: 10.93,
    damageMultiplier: 7.17,
    armorRating: 66.2,
    magicResistRating: 60,
    enrageTimerSec: 88,
  },
  {
    waveNumber: 65,
    playerCount: 1,
    hpMultiplier: 8.8,
    damageMultiplier: 6.2,
    armorRating: 67,
    magicResistRating: 60.75,
    enrageTimerSec: 87.5,
  },
  {
    waveNumber: 65,
    playerCount: 2,
    hpMultiplier: 9.55,
    damageMultiplier: 6.55,
    armorRating: 67,
    magicResistRating: 60.75,
    enrageTimerSec: 87.5,
  },
  {
    waveNumber: 65,
    playerCount: 3,
    hpMultiplier: 10.3,
    damageMultiplier: 6.9,
    armorRating: 67,
    magicResistRating: 60.75,
    enrageTimerSec: 87.5,
  },
  {
    waveNumber: 65,
    playerCount: 4,
    hpMultiplier: 11.05,
    damageMultiplier: 7.25,
    armorRating: 67,
    magicResistRating: 60.75,
    enrageTimerSec: 87.5,
  },
  {
    waveNumber: 66,
    playerCount: 1,
    hpMultiplier: 8.92,
    damageMultiplier: 6.28,
    armorRating: 67.80000000000001,
    magicResistRating: 61.5,
    enrageTimerSec: 87,
  },
  {
    waveNumber: 66,
    playerCount: 2,
    hpMultiplier: 9.67,
    damageMultiplier: 6.63,
    armorRating: 67.80000000000001,
    magicResistRating: 61.5,
    enrageTimerSec: 87,
  },
  {
    waveNumber: 66,
    playerCount: 3,
    hpMultiplier: 10.42,
    damageMultiplier: 6.98,
    armorRating: 67.80000000000001,
    magicResistRating: 61.5,
    enrageTimerSec: 87,
  },
  {
    waveNumber: 66,
    playerCount: 4,
    hpMultiplier: 11.17,
    damageMultiplier: 7.33,
    armorRating: 67.80000000000001,
    magicResistRating: 61.5,
    enrageTimerSec: 87,
  },
  {
    waveNumber: 67,
    playerCount: 1,
    hpMultiplier: 9.04,
    damageMultiplier: 6.36,
    armorRating: 68.6,
    magicResistRating: 62.25,
    enrageTimerSec: 86.5,
  },
  {
    waveNumber: 67,
    playerCount: 2,
    hpMultiplier: 9.79,
    damageMultiplier: 6.71,
    armorRating: 68.6,
    magicResistRating: 62.25,
    enrageTimerSec: 86.5,
  },
  {
    waveNumber: 67,
    playerCount: 3,
    hpMultiplier: 10.54,
    damageMultiplier: 7.06,
    armorRating: 68.6,
    magicResistRating: 62.25,
    enrageTimerSec: 86.5,
  },
  {
    waveNumber: 67,
    playerCount: 4,
    hpMultiplier: 11.29,
    damageMultiplier: 7.41,
    armorRating: 68.6,
    magicResistRating: 62.25,
    enrageTimerSec: 86.5,
  },
  {
    waveNumber: 68,
    playerCount: 1,
    hpMultiplier: 9.16,
    damageMultiplier: 6.44,
    armorRating: 69.4,
    magicResistRating: 63,
    enrageTimerSec: 86,
  },
  {
    waveNumber: 68,
    playerCount: 2,
    hpMultiplier: 9.91,
    damageMultiplier: 6.79,
    armorRating: 69.4,
    magicResistRating: 63,
    enrageTimerSec: 86,
  },
  {
    waveNumber: 68,
    playerCount: 3,
    hpMultiplier: 10.66,
    damageMultiplier: 7.14,
    armorRating: 69.4,
    magicResistRating: 63,
    enrageTimerSec: 86,
  },
  {
    waveNumber: 68,
    playerCount: 4,
    hpMultiplier: 11.41,
    damageMultiplier: 7.49,
    armorRating: 69.4,
    magicResistRating: 63,
    enrageTimerSec: 86,
  },
  {
    waveNumber: 69,
    playerCount: 1,
    hpMultiplier: 9.28,
    damageMultiplier: 6.52,
    armorRating: 70.2,
    magicResistRating: 63.75,
    enrageTimerSec: 85.5,
  },
  {
    waveNumber: 69,
    playerCount: 2,
    hpMultiplier: 10.03,
    damageMultiplier: 6.87,
    armorRating: 70.2,
    magicResistRating: 63.75,
    enrageTimerSec: 85.5,
  },
  {
    waveNumber: 69,
    playerCount: 3,
    hpMultiplier: 10.78,
    damageMultiplier: 7.22,
    armorRating: 70.2,
    magicResistRating: 63.75,
    enrageTimerSec: 85.5,
  },
  {
    waveNumber: 69,
    playerCount: 4,
    hpMultiplier: 11.53,
    damageMultiplier: 7.57,
    armorRating: 70.2,
    magicResistRating: 63.75,
    enrageTimerSec: 85.5,
  },
  {
    waveNumber: 70,
    playerCount: 1,
    hpMultiplier: 9.4,
    damageMultiplier: 6.6,
    armorRating: 71,
    magicResistRating: 64.5,
    enrageTimerSec: 85,
  },
  {
    waveNumber: 70,
    playerCount: 2,
    hpMultiplier: 10.15,
    damageMultiplier: 6.95,
    armorRating: 71,
    magicResistRating: 64.5,
    enrageTimerSec: 85,
  },
  {
    waveNumber: 70,
    playerCount: 3,
    hpMultiplier: 10.9,
    damageMultiplier: 7.3,
    armorRating: 71,
    magicResistRating: 64.5,
    enrageTimerSec: 85,
  },
  {
    waveNumber: 70,
    playerCount: 4,
    hpMultiplier: 11.65,
    damageMultiplier: 7.65,
    armorRating: 71,
    magicResistRating: 64.5,
    enrageTimerSec: 85,
  },
  {
    waveNumber: 71,
    playerCount: 1,
    hpMultiplier: 9.52,
    damageMultiplier: 6.68,
    armorRating: 71.80000000000001,
    magicResistRating: 65.25,
    enrageTimerSec: 84.5,
  },
  {
    waveNumber: 71,
    playerCount: 2,
    hpMultiplier: 10.27,
    damageMultiplier: 7.03,
    armorRating: 71.80000000000001,
    magicResistRating: 65.25,
    enrageTimerSec: 84.5,
  },
  {
    waveNumber: 71,
    playerCount: 3,
    hpMultiplier: 11.02,
    damageMultiplier: 7.38,
    armorRating: 71.80000000000001,
    magicResistRating: 65.25,
    enrageTimerSec: 84.5,
  },
  {
    waveNumber: 71,
    playerCount: 4,
    hpMultiplier: 11.77,
    damageMultiplier: 7.73,
    armorRating: 71.80000000000001,
    magicResistRating: 65.25,
    enrageTimerSec: 84.5,
  },
  {
    waveNumber: 72,
    playerCount: 1,
    hpMultiplier: 9.64,
    damageMultiplier: 6.76,
    armorRating: 72.6,
    magicResistRating: 66,
    enrageTimerSec: 84,
  },
  {
    waveNumber: 72,
    playerCount: 2,
    hpMultiplier: 10.39,
    damageMultiplier: 7.11,
    armorRating: 72.6,
    magicResistRating: 66,
    enrageTimerSec: 84,
  },
  {
    waveNumber: 72,
    playerCount: 3,
    hpMultiplier: 11.14,
    damageMultiplier: 7.46,
    armorRating: 72.6,
    magicResistRating: 66,
    enrageTimerSec: 84,
  },
  {
    waveNumber: 72,
    playerCount: 4,
    hpMultiplier: 11.89,
    damageMultiplier: 7.81,
    armorRating: 72.6,
    magicResistRating: 66,
    enrageTimerSec: 84,
  },
  {
    waveNumber: 73,
    playerCount: 1,
    hpMultiplier: 9.76,
    damageMultiplier: 6.84,
    armorRating: 73.4,
    magicResistRating: 66.75,
    enrageTimerSec: 83.5,
  },
  {
    waveNumber: 73,
    playerCount: 2,
    hpMultiplier: 10.51,
    damageMultiplier: 7.19,
    armorRating: 73.4,
    magicResistRating: 66.75,
    enrageTimerSec: 83.5,
  },
  {
    waveNumber: 73,
    playerCount: 3,
    hpMultiplier: 11.26,
    damageMultiplier: 7.54,
    armorRating: 73.4,
    magicResistRating: 66.75,
    enrageTimerSec: 83.5,
  },
  {
    waveNumber: 73,
    playerCount: 4,
    hpMultiplier: 12.01,
    damageMultiplier: 7.89,
    armorRating: 73.4,
    magicResistRating: 66.75,
    enrageTimerSec: 83.5,
  },
  {
    waveNumber: 74,
    playerCount: 1,
    hpMultiplier: 9.88,
    damageMultiplier: 6.92,
    armorRating: 74.2,
    magicResistRating: 67.5,
    enrageTimerSec: 83,
  },
  {
    waveNumber: 74,
    playerCount: 2,
    hpMultiplier: 10.63,
    damageMultiplier: 7.27,
    armorRating: 74.2,
    magicResistRating: 67.5,
    enrageTimerSec: 83,
  },
  {
    waveNumber: 74,
    playerCount: 3,
    hpMultiplier: 11.38,
    damageMultiplier: 7.62,
    armorRating: 74.2,
    magicResistRating: 67.5,
    enrageTimerSec: 83,
  },
  {
    waveNumber: 74,
    playerCount: 4,
    hpMultiplier: 12.13,
    damageMultiplier: 7.97,
    armorRating: 74.2,
    magicResistRating: 67.5,
    enrageTimerSec: 83,
  },
  {
    waveNumber: 75,
    playerCount: 1,
    hpMultiplier: 10,
    damageMultiplier: 7,
    armorRating: 75,
    magicResistRating: 68.25,
    enrageTimerSec: 82.5,
  },
  {
    waveNumber: 75,
    playerCount: 2,
    hpMultiplier: 10.75,
    damageMultiplier: 7.35,
    armorRating: 75,
    magicResistRating: 68.25,
    enrageTimerSec: 82.5,
  },
  {
    waveNumber: 75,
    playerCount: 3,
    hpMultiplier: 11.5,
    damageMultiplier: 7.7,
    armorRating: 75,
    magicResistRating: 68.25,
    enrageTimerSec: 82.5,
  },
  {
    waveNumber: 75,
    playerCount: 4,
    hpMultiplier: 12.25,
    damageMultiplier: 8.05,
    armorRating: 75,
    magicResistRating: 68.25,
    enrageTimerSec: 82.5,
  },
  {
    waveNumber: 76,
    playerCount: 1,
    hpMultiplier: 10.12,
    damageMultiplier: 7.08,
    armorRating: 75.80000000000001,
    magicResistRating: 69,
    enrageTimerSec: 82,
  },
  {
    waveNumber: 76,
    playerCount: 2,
    hpMultiplier: 10.87,
    damageMultiplier: 7.43,
    armorRating: 75.80000000000001,
    magicResistRating: 69,
    enrageTimerSec: 82,
  },
  {
    waveNumber: 76,
    playerCount: 3,
    hpMultiplier: 11.62,
    damageMultiplier: 7.78,
    armorRating: 75.80000000000001,
    magicResistRating: 69,
    enrageTimerSec: 82,
  },
  {
    waveNumber: 76,
    playerCount: 4,
    hpMultiplier: 12.37,
    damageMultiplier: 8.13,
    armorRating: 75.80000000000001,
    magicResistRating: 69,
    enrageTimerSec: 82,
  },
  {
    waveNumber: 77,
    playerCount: 1,
    hpMultiplier: 10.24,
    damageMultiplier: 7.16,
    armorRating: 76.6,
    magicResistRating: 69.75,
    enrageTimerSec: 81.5,
  },
  {
    waveNumber: 77,
    playerCount: 2,
    hpMultiplier: 10.99,
    damageMultiplier: 7.51,
    armorRating: 76.6,
    magicResistRating: 69.75,
    enrageTimerSec: 81.5,
  },
  {
    waveNumber: 77,
    playerCount: 3,
    hpMultiplier: 11.74,
    damageMultiplier: 7.86,
    armorRating: 76.6,
    magicResistRating: 69.75,
    enrageTimerSec: 81.5,
  },
  {
    waveNumber: 77,
    playerCount: 4,
    hpMultiplier: 12.49,
    damageMultiplier: 8.21,
    armorRating: 76.6,
    magicResistRating: 69.75,
    enrageTimerSec: 81.5,
  },
  {
    waveNumber: 78,
    playerCount: 1,
    hpMultiplier: 10.36,
    damageMultiplier: 7.24,
    armorRating: 77.4,
    magicResistRating: 70.5,
    enrageTimerSec: 81,
  },
  {
    waveNumber: 78,
    playerCount: 2,
    hpMultiplier: 11.11,
    damageMultiplier: 7.59,
    armorRating: 77.4,
    magicResistRating: 70.5,
    enrageTimerSec: 81,
  },
  {
    waveNumber: 78,
    playerCount: 3,
    hpMultiplier: 11.86,
    damageMultiplier: 7.94,
    armorRating: 77.4,
    magicResistRating: 70.5,
    enrageTimerSec: 81,
  },
  {
    waveNumber: 78,
    playerCount: 4,
    hpMultiplier: 12.61,
    damageMultiplier: 8.29,
    armorRating: 77.4,
    magicResistRating: 70.5,
    enrageTimerSec: 81,
  },
  {
    waveNumber: 79,
    playerCount: 1,
    hpMultiplier: 10.48,
    damageMultiplier: 7.32,
    armorRating: 78.2,
    magicResistRating: 71.25,
    enrageTimerSec: 80.5,
  },
  {
    waveNumber: 79,
    playerCount: 2,
    hpMultiplier: 11.23,
    damageMultiplier: 7.67,
    armorRating: 78.2,
    magicResistRating: 71.25,
    enrageTimerSec: 80.5,
  },
  {
    waveNumber: 79,
    playerCount: 3,
    hpMultiplier: 11.98,
    damageMultiplier: 8.02,
    armorRating: 78.2,
    magicResistRating: 71.25,
    enrageTimerSec: 80.5,
  },
  {
    waveNumber: 79,
    playerCount: 4,
    hpMultiplier: 12.73,
    damageMultiplier: 8.37,
    armorRating: 78.2,
    magicResistRating: 71.25,
    enrageTimerSec: 80.5,
  },
  {
    waveNumber: 80,
    playerCount: 1,
    hpMultiplier: 10.6,
    damageMultiplier: 7.4,
    armorRating: 79,
    magicResistRating: 72,
    enrageTimerSec: 80,
  },
  {
    waveNumber: 80,
    playerCount: 2,
    hpMultiplier: 11.35,
    damageMultiplier: 7.75,
    armorRating: 79,
    magicResistRating: 72,
    enrageTimerSec: 80,
  },
  {
    waveNumber: 80,
    playerCount: 3,
    hpMultiplier: 12.1,
    damageMultiplier: 8.1,
    armorRating: 79,
    magicResistRating: 72,
    enrageTimerSec: 80,
  },
  {
    waveNumber: 80,
    playerCount: 4,
    hpMultiplier: 12.85,
    damageMultiplier: 8.45,
    armorRating: 79,
    magicResistRating: 72,
    enrageTimerSec: 80,
  },
  {
    waveNumber: 81,
    playerCount: 1,
    hpMultiplier: 10.72,
    damageMultiplier: 7.48,
    armorRating: 79.8,
    magicResistRating: 72.75,
    enrageTimerSec: 79.5,
  },
  {
    waveNumber: 81,
    playerCount: 2,
    hpMultiplier: 11.47,
    damageMultiplier: 7.83,
    armorRating: 79.8,
    magicResistRating: 72.75,
    enrageTimerSec: 79.5,
  },
  {
    waveNumber: 81,
    playerCount: 3,
    hpMultiplier: 12.22,
    damageMultiplier: 8.18,
    armorRating: 79.8,
    magicResistRating: 72.75,
    enrageTimerSec: 79.5,
  },
  {
    waveNumber: 81,
    playerCount: 4,
    hpMultiplier: 12.97,
    damageMultiplier: 8.53,
    armorRating: 79.8,
    magicResistRating: 72.75,
    enrageTimerSec: 79.5,
  },
  {
    waveNumber: 82,
    playerCount: 1,
    hpMultiplier: 10.84,
    damageMultiplier: 7.56,
    armorRating: 80.60000000000001,
    magicResistRating: 73.5,
    enrageTimerSec: 79,
  },
  {
    waveNumber: 82,
    playerCount: 2,
    hpMultiplier: 11.59,
    damageMultiplier: 7.91,
    armorRating: 80.60000000000001,
    magicResistRating: 73.5,
    enrageTimerSec: 79,
  },
  {
    waveNumber: 82,
    playerCount: 3,
    hpMultiplier: 12.34,
    damageMultiplier: 8.26,
    armorRating: 80.60000000000001,
    magicResistRating: 73.5,
    enrageTimerSec: 79,
  },
  {
    waveNumber: 82,
    playerCount: 4,
    hpMultiplier: 13.09,
    damageMultiplier: 8.61,
    armorRating: 80.60000000000001,
    magicResistRating: 73.5,
    enrageTimerSec: 79,
  },
  {
    waveNumber: 83,
    playerCount: 1,
    hpMultiplier: 10.96,
    damageMultiplier: 7.64,
    armorRating: 81.4,
    magicResistRating: 74.25,
    enrageTimerSec: 78.5,
  },
  {
    waveNumber: 83,
    playerCount: 2,
    hpMultiplier: 11.71,
    damageMultiplier: 7.99,
    armorRating: 81.4,
    magicResistRating: 74.25,
    enrageTimerSec: 78.5,
  },
  {
    waveNumber: 83,
    playerCount: 3,
    hpMultiplier: 12.46,
    damageMultiplier: 8.34,
    armorRating: 81.4,
    magicResistRating: 74.25,
    enrageTimerSec: 78.5,
  },
  {
    waveNumber: 83,
    playerCount: 4,
    hpMultiplier: 13.21,
    damageMultiplier: 8.69,
    armorRating: 81.4,
    magicResistRating: 74.25,
    enrageTimerSec: 78.5,
  },
  {
    waveNumber: 84,
    playerCount: 1,
    hpMultiplier: 11.08,
    damageMultiplier: 7.72,
    armorRating: 82.2,
    magicResistRating: 75,
    enrageTimerSec: 78,
  },
  {
    waveNumber: 84,
    playerCount: 2,
    hpMultiplier: 11.83,
    damageMultiplier: 8.07,
    armorRating: 82.2,
    magicResistRating: 75,
    enrageTimerSec: 78,
  },
  {
    waveNumber: 84,
    playerCount: 3,
    hpMultiplier: 12.58,
    damageMultiplier: 8.42,
    armorRating: 82.2,
    magicResistRating: 75,
    enrageTimerSec: 78,
  },
  {
    waveNumber: 84,
    playerCount: 4,
    hpMultiplier: 13.33,
    damageMultiplier: 8.77,
    armorRating: 82.2,
    magicResistRating: 75,
    enrageTimerSec: 78,
  },
  {
    waveNumber: 85,
    playerCount: 1,
    hpMultiplier: 11.2,
    damageMultiplier: 7.8,
    armorRating: 83,
    magicResistRating: 75.75,
    enrageTimerSec: 77.5,
  },
  {
    waveNumber: 85,
    playerCount: 2,
    hpMultiplier: 11.95,
    damageMultiplier: 8.15,
    armorRating: 83,
    magicResistRating: 75.75,
    enrageTimerSec: 77.5,
  },
  {
    waveNumber: 85,
    playerCount: 3,
    hpMultiplier: 12.7,
    damageMultiplier: 8.5,
    armorRating: 83,
    magicResistRating: 75.75,
    enrageTimerSec: 77.5,
  },
  {
    waveNumber: 85,
    playerCount: 4,
    hpMultiplier: 13.45,
    damageMultiplier: 8.85,
    armorRating: 83,
    magicResistRating: 75.75,
    enrageTimerSec: 77.5,
  },
  {
    waveNumber: 86,
    playerCount: 1,
    hpMultiplier: 11.32,
    damageMultiplier: 7.88,
    armorRating: 83.8,
    magicResistRating: 76.5,
    enrageTimerSec: 77,
  },
  {
    waveNumber: 86,
    playerCount: 2,
    hpMultiplier: 12.07,
    damageMultiplier: 8.23,
    armorRating: 83.8,
    magicResistRating: 76.5,
    enrageTimerSec: 77,
  },
  {
    waveNumber: 86,
    playerCount: 3,
    hpMultiplier: 12.82,
    damageMultiplier: 8.58,
    armorRating: 83.8,
    magicResistRating: 76.5,
    enrageTimerSec: 77,
  },
  {
    waveNumber: 86,
    playerCount: 4,
    hpMultiplier: 13.57,
    damageMultiplier: 8.93,
    armorRating: 83.8,
    magicResistRating: 76.5,
    enrageTimerSec: 77,
  },
  {
    waveNumber: 87,
    playerCount: 1,
    hpMultiplier: 11.44,
    damageMultiplier: 7.96,
    armorRating: 84.60000000000001,
    magicResistRating: 77.25,
    enrageTimerSec: 76.5,
  },
  {
    waveNumber: 87,
    playerCount: 2,
    hpMultiplier: 12.19,
    damageMultiplier: 8.31,
    armorRating: 84.60000000000001,
    magicResistRating: 77.25,
    enrageTimerSec: 76.5,
  },
  {
    waveNumber: 87,
    playerCount: 3,
    hpMultiplier: 12.94,
    damageMultiplier: 8.66,
    armorRating: 84.60000000000001,
    magicResistRating: 77.25,
    enrageTimerSec: 76.5,
  },
  {
    waveNumber: 87,
    playerCount: 4,
    hpMultiplier: 13.69,
    damageMultiplier: 9.01,
    armorRating: 84.60000000000001,
    magicResistRating: 77.25,
    enrageTimerSec: 76.5,
  },
  {
    waveNumber: 88,
    playerCount: 1,
    hpMultiplier: 11.56,
    damageMultiplier: 8.04,
    armorRating: 85.4,
    magicResistRating: 78,
    enrageTimerSec: 76,
  },
  {
    waveNumber: 88,
    playerCount: 2,
    hpMultiplier: 12.31,
    damageMultiplier: 8.39,
    armorRating: 85.4,
    magicResistRating: 78,
    enrageTimerSec: 76,
  },
  {
    waveNumber: 88,
    playerCount: 3,
    hpMultiplier: 13.06,
    damageMultiplier: 8.74,
    armorRating: 85.4,
    magicResistRating: 78,
    enrageTimerSec: 76,
  },
  {
    waveNumber: 88,
    playerCount: 4,
    hpMultiplier: 13.81,
    damageMultiplier: 9.09,
    armorRating: 85.4,
    magicResistRating: 78,
    enrageTimerSec: 76,
  },
  {
    waveNumber: 89,
    playerCount: 1,
    hpMultiplier: 11.68,
    damageMultiplier: 8.12,
    armorRating: 86.2,
    magicResistRating: 78.75,
    enrageTimerSec: 75.5,
  },
  {
    waveNumber: 89,
    playerCount: 2,
    hpMultiplier: 12.43,
    damageMultiplier: 8.47,
    armorRating: 86.2,
    magicResistRating: 78.75,
    enrageTimerSec: 75.5,
  },
  {
    waveNumber: 89,
    playerCount: 3,
    hpMultiplier: 13.18,
    damageMultiplier: 8.82,
    armorRating: 86.2,
    magicResistRating: 78.75,
    enrageTimerSec: 75.5,
  },
  {
    waveNumber: 89,
    playerCount: 4,
    hpMultiplier: 13.93,
    damageMultiplier: 9.17,
    armorRating: 86.2,
    magicResistRating: 78.75,
    enrageTimerSec: 75.5,
  },
  {
    waveNumber: 90,
    playerCount: 1,
    hpMultiplier: 11.8,
    damageMultiplier: 8.2,
    armorRating: 87,
    magicResistRating: 79.5,
    enrageTimerSec: 75,
  },
  {
    waveNumber: 90,
    playerCount: 2,
    hpMultiplier: 12.55,
    damageMultiplier: 8.55,
    armorRating: 87,
    magicResistRating: 79.5,
    enrageTimerSec: 75,
  },
  {
    waveNumber: 90,
    playerCount: 3,
    hpMultiplier: 13.3,
    damageMultiplier: 8.9,
    armorRating: 87,
    magicResistRating: 79.5,
    enrageTimerSec: 75,
  },
  {
    waveNumber: 90,
    playerCount: 4,
    hpMultiplier: 14.05,
    damageMultiplier: 9.25,
    armorRating: 87,
    magicResistRating: 79.5,
    enrageTimerSec: 75,
  },
  {
    waveNumber: 91,
    playerCount: 1,
    hpMultiplier: 11.92,
    damageMultiplier: 8.28,
    armorRating: 87.8,
    magicResistRating: 80.25,
    enrageTimerSec: 74.5,
  },
  {
    waveNumber: 91,
    playerCount: 2,
    hpMultiplier: 12.67,
    damageMultiplier: 8.63,
    armorRating: 87.8,
    magicResistRating: 80.25,
    enrageTimerSec: 74.5,
  },
  {
    waveNumber: 91,
    playerCount: 3,
    hpMultiplier: 13.42,
    damageMultiplier: 8.98,
    armorRating: 87.8,
    magicResistRating: 80.25,
    enrageTimerSec: 74.5,
  },
  {
    waveNumber: 91,
    playerCount: 4,
    hpMultiplier: 14.17,
    damageMultiplier: 9.33,
    armorRating: 87.8,
    magicResistRating: 80.25,
    enrageTimerSec: 74.5,
  },
  {
    waveNumber: 92,
    playerCount: 1,
    hpMultiplier: 12.04,
    damageMultiplier: 8.36,
    armorRating: 88.60000000000001,
    magicResistRating: 81,
    enrageTimerSec: 74,
  },
  {
    waveNumber: 92,
    playerCount: 2,
    hpMultiplier: 12.79,
    damageMultiplier: 8.71,
    armorRating: 88.60000000000001,
    magicResistRating: 81,
    enrageTimerSec: 74,
  },
  {
    waveNumber: 92,
    playerCount: 3,
    hpMultiplier: 13.54,
    damageMultiplier: 9.06,
    armorRating: 88.60000000000001,
    magicResistRating: 81,
    enrageTimerSec: 74,
  },
  {
    waveNumber: 92,
    playerCount: 4,
    hpMultiplier: 14.29,
    damageMultiplier: 9.41,
    armorRating: 88.60000000000001,
    magicResistRating: 81,
    enrageTimerSec: 74,
  },
  {
    waveNumber: 93,
    playerCount: 1,
    hpMultiplier: 12.16,
    damageMultiplier: 8.44,
    armorRating: 89.4,
    magicResistRating: 81.75,
    enrageTimerSec: 73.5,
  },
  {
    waveNumber: 93,
    playerCount: 2,
    hpMultiplier: 12.91,
    damageMultiplier: 8.79,
    armorRating: 89.4,
    magicResistRating: 81.75,
    enrageTimerSec: 73.5,
  },
  {
    waveNumber: 93,
    playerCount: 3,
    hpMultiplier: 13.66,
    damageMultiplier: 9.14,
    armorRating: 89.4,
    magicResistRating: 81.75,
    enrageTimerSec: 73.5,
  },
  {
    waveNumber: 93,
    playerCount: 4,
    hpMultiplier: 14.41,
    damageMultiplier: 9.49,
    armorRating: 89.4,
    magicResistRating: 81.75,
    enrageTimerSec: 73.5,
  },
  {
    waveNumber: 94,
    playerCount: 1,
    hpMultiplier: 12.28,
    damageMultiplier: 8.52,
    armorRating: 90,
    magicResistRating: 82.5,
    enrageTimerSec: 73,
  },
  {
    waveNumber: 94,
    playerCount: 2,
    hpMultiplier: 13.03,
    damageMultiplier: 8.87,
    armorRating: 90,
    magicResistRating: 82.5,
    enrageTimerSec: 73,
  },
  {
    waveNumber: 94,
    playerCount: 3,
    hpMultiplier: 13.78,
    damageMultiplier: 9.22,
    armorRating: 90,
    magicResistRating: 82.5,
    enrageTimerSec: 73,
  },
  {
    waveNumber: 94,
    playerCount: 4,
    hpMultiplier: 14.53,
    damageMultiplier: 9.57,
    armorRating: 90,
    magicResistRating: 82.5,
    enrageTimerSec: 73,
  },
  {
    waveNumber: 95,
    playerCount: 1,
    hpMultiplier: 12.4,
    damageMultiplier: 8.6,
    armorRating: 90,
    magicResistRating: 83.25,
    enrageTimerSec: 72.5,
  },
  {
    waveNumber: 95,
    playerCount: 2,
    hpMultiplier: 13.15,
    damageMultiplier: 8.95,
    armorRating: 90,
    magicResistRating: 83.25,
    enrageTimerSec: 72.5,
  },
  {
    waveNumber: 95,
    playerCount: 3,
    hpMultiplier: 13.9,
    damageMultiplier: 9.3,
    armorRating: 90,
    magicResistRating: 83.25,
    enrageTimerSec: 72.5,
  },
  {
    waveNumber: 95,
    playerCount: 4,
    hpMultiplier: 14.65,
    damageMultiplier: 9.65,
    armorRating: 90,
    magicResistRating: 83.25,
    enrageTimerSec: 72.5,
  },
  {
    waveNumber: 96,
    playerCount: 1,
    hpMultiplier: 12.52,
    damageMultiplier: 8.68,
    armorRating: 90,
    magicResistRating: 84,
    enrageTimerSec: 72,
  },
  {
    waveNumber: 96,
    playerCount: 2,
    hpMultiplier: 13.27,
    damageMultiplier: 9.03,
    armorRating: 90,
    magicResistRating: 84,
    enrageTimerSec: 72,
  },
  {
    waveNumber: 96,
    playerCount: 3,
    hpMultiplier: 14.02,
    damageMultiplier: 9.38,
    armorRating: 90,
    magicResistRating: 84,
    enrageTimerSec: 72,
  },
  {
    waveNumber: 96,
    playerCount: 4,
    hpMultiplier: 14.77,
    damageMultiplier: 9.73,
    armorRating: 90,
    magicResistRating: 84,
    enrageTimerSec: 72,
  },
  {
    waveNumber: 97,
    playerCount: 1,
    hpMultiplier: 12.64,
    damageMultiplier: 8.76,
    armorRating: 90,
    magicResistRating: 84.75,
    enrageTimerSec: 71.5,
  },
  {
    waveNumber: 97,
    playerCount: 2,
    hpMultiplier: 13.39,
    damageMultiplier: 9.11,
    armorRating: 90,
    magicResistRating: 84.75,
    enrageTimerSec: 71.5,
  },
  {
    waveNumber: 97,
    playerCount: 3,
    hpMultiplier: 14.14,
    damageMultiplier: 9.46,
    armorRating: 90,
    magicResistRating: 84.75,
    enrageTimerSec: 71.5,
  },
  {
    waveNumber: 97,
    playerCount: 4,
    hpMultiplier: 14.89,
    damageMultiplier: 9.81,
    armorRating: 90,
    magicResistRating: 84.75,
    enrageTimerSec: 71.5,
  },
  {
    waveNumber: 98,
    playerCount: 1,
    hpMultiplier: 12.76,
    damageMultiplier: 8.84,
    armorRating: 90,
    magicResistRating: 85.5,
    enrageTimerSec: 71,
  },
  {
    waveNumber: 98,
    playerCount: 2,
    hpMultiplier: 13.51,
    damageMultiplier: 9.19,
    armorRating: 90,
    magicResistRating: 85.5,
    enrageTimerSec: 71,
  },
  {
    waveNumber: 98,
    playerCount: 3,
    hpMultiplier: 14.26,
    damageMultiplier: 9.54,
    armorRating: 90,
    magicResistRating: 85.5,
    enrageTimerSec: 71,
  },
  {
    waveNumber: 98,
    playerCount: 4,
    hpMultiplier: 15.01,
    damageMultiplier: 9.89,
    armorRating: 90,
    magicResistRating: 85.5,
    enrageTimerSec: 71,
  },
  {
    waveNumber: 99,
    playerCount: 1,
    hpMultiplier: 12.88,
    damageMultiplier: 8.92,
    armorRating: 90,
    magicResistRating: 86.25,
    enrageTimerSec: 70.5,
  },
  {
    waveNumber: 99,
    playerCount: 2,
    hpMultiplier: 13.63,
    damageMultiplier: 9.27,
    armorRating: 90,
    magicResistRating: 86.25,
    enrageTimerSec: 70.5,
  },
  {
    waveNumber: 99,
    playerCount: 3,
    hpMultiplier: 14.38,
    damageMultiplier: 9.62,
    armorRating: 90,
    magicResistRating: 86.25,
    enrageTimerSec: 70.5,
  },
  {
    waveNumber: 99,
    playerCount: 4,
    hpMultiplier: 15.13,
    damageMultiplier: 9.97,
    armorRating: 90,
    magicResistRating: 86.25,
    enrageTimerSec: 70.5,
  },
  {
    waveNumber: 100,
    playerCount: 1,
    hpMultiplier: 13,
    damageMultiplier: 9,
    armorRating: 90,
    magicResistRating: 87,
    enrageTimerSec: 70,
  },
  {
    waveNumber: 100,
    playerCount: 2,
    hpMultiplier: 13.75,
    damageMultiplier: 9.35,
    armorRating: 90,
    magicResistRating: 87,
    enrageTimerSec: 70,
  },
  {
    waveNumber: 100,
    playerCount: 3,
    hpMultiplier: 14.5,
    damageMultiplier: 9.7,
    armorRating: 90,
    magicResistRating: 87,
    enrageTimerSec: 70,
  },
  {
    waveNumber: 100,
    playerCount: 4,
    hpMultiplier: 15.25,
    damageMultiplier: 10.05,
    armorRating: 90,
    magicResistRating: 87,
    enrageTimerSec: 70,
  },
];

export class RaidBossScalingCalculator {
  static getScaling(wave: number, players: number): RaidScalingProfile {
    const match = RAID_SCALING_PROFILES.find(s => s.waveNumber === wave && s.playerCount === players);
    return match || RAID_SCALING_PROFILES[0]!;
  }

  static evaluateRaidDifficultyIndex_1(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_2(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_3(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_4(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_5(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_6(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_7(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_8(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_9(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_10(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_11(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_12(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_13(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_14(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_15(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_16(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_17(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_18(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_19(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_20(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_21(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_22(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_23(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_24(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_25(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_26(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_27(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_28(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_29(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_30(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_31(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_32(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_33(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_34(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_35(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_36(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_37(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_38(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_39(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_40(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_41(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_42(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_43(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_44(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_45(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_46(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_47(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_48(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_49(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_50(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_51(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_52(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_53(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_54(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_55(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_56(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_57(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_58(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_59(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

  static evaluateRaidDifficultyIndex_60(profile: RaidScalingProfile, teamDps: number): { isClearing: boolean; timeToKillSec: number } {
    const effectiveHp = 50000 * profile.hpMultiplier;
    const ttk = effectiveHp / Math.max(1, teamDps);
    return { isClearing: ttk <= profile.enrageTimerSec, timeToKillSec: Math.round(ttk * 10) / 10 };
  }

}