import { DamageType, TowerType, StatusEffect } from '../engine/ecs/Components';

export interface TowerUpgradeNode {
  tier: number;
  branchName: string;
  cost: number;
  damage: number;
  range: number;
  fireRate: number;
  damageType: DamageType;
  splashRadius: number;
  chainCount: number;
  chainDecay: number;
  effects: StatusEffect[];
  description: string;
}

export interface TowerConfig {
  type: TowerType;
  name: string;
  description: string;
  baseCost: number;
  baseDamage: number;
  baseRange: number;
  baseFireRate: number;
  damageType: DamageType;
  splashRadius: number;
  chainCount: number;
  chainDecay: number;
  baseEffects: StatusEffect[];
  upgrades: {
    tier2: TowerUpgradeNode;
    tier3BranchA: TowerUpgradeNode;
    tier3BranchB: TowerUpgradeNode;
    tier4A: TowerUpgradeNode;
    tier4B: TowerUpgradeNode;
  };
}

export const TOWER_DEFINITIONS: Record<TowerType, TowerConfig> = {
  [TowerType.ARCHER]: {
    type: TowerType.ARCHER,
    name: 'Archer Watchtower',
    description: 'Rapid single-target physical sniper tower with long sight lines.',
    baseCost: 100,
    baseDamage: 25,
    baseRange: 160,
    baseFireRate: 1.5,
    damageType: DamageType.PHYSICAL,
    splashRadius: 0,
    chainCount: 0,
    chainDecay: 0,
    baseEffects: [],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Marksman Post',
        cost: 120,
        damage: 45,
        range: 180,
        fireRate: 1.8,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Enhanced bow strings increasing damage and range.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'Longbow Sniper',
        cost: 240,
        damage: 120,
        range: 260,
        fireRate: 1.0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Extreme range sniper that pierces through heavy armor.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Repeating Crossbow',
        cost: 220,
        damage: 35,
        range: 160,
        fireRate: 4.0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Fires a continuous hail of bolts at high speed.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Grand Eagle Eye',
        cost: 500,
        damage: 320,
        range: 340,
        fireRate: 1.2,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Devastating armor-piercing longshot with critical strike mastery.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Ballista Gatling',
        cost: 480,
        damage: 75,
        range: 190,
        fireRate: 6.5,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Twin mechanical ballistas shredding entire enemy columns.',
      },
    },
  },

  [TowerType.MAGE]: {
    type: TowerType.MAGE,
    name: 'Arcane Spire',
    description: 'Channels destructive magical orbs that burst into area-of-effect splash.',
    baseCost: 150,
    baseDamage: 40,
    baseRange: 140,
    baseFireRate: 0.8,
    damageType: DamageType.MAGIC,
    splashRadius: 48,
    chainCount: 0,
    chainDecay: 0,
    baseEffects: [],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Aether Sanctum',
        cost: 160,
        damage: 75,
        range: 155,
        fireRate: 1.0,
        damageType: DamageType.MAGIC,
        splashRadius: 56,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Expanded mana reservoir producing larger arcane explosions.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'Pyroclasm Forge',
        cost: 280,
        damage: 130,
        range: 160,
        fireRate: 0.9,
        damageType: DamageType.MAGIC,
        splashRadius: 64,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'burn_dot',
            type: 'BURN',
            value: 20,
            durationMs: 3000,
            remainingMs: 3000,
            tickIntervalMs: 500,
            tickDamage: 15,
            tickDamageType: DamageType.MAGIC,
          },
        ],
        description: 'Engulfs enemies in molten fire that continues burning over time.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Void Singularity',
        cost: 300,
        damage: 160,
        range: 145,
        fireRate: 0.7,
        damageType: DamageType.MAGIC,
        splashRadius: 72,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'armor_shred',
            type: 'ARMOR_SHRED',
            value: 0.35,
            durationMs: 4000,
            remainingMs: 4000,
          },
        ],
        description: 'Collapses the fabric of space, shredding enemy resistance by 35%.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Solar Cataclysm',
        cost: 600,
        damage: 380,
        range: 180,
        fireRate: 1.1,
        damageType: DamageType.MAGIC,
        splashRadius: 88,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'solar_flare',
            type: 'BURN',
            value: 50,
            durationMs: 4000,
            remainingMs: 4000,
            tickIntervalMs: 500,
            tickDamage: 40,
            tickDamageType: DamageType.MAGIC,
          },
        ],
        description: 'Calls down a solar flare that obliterates massive hordes.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Astral Rift',
        cost: 650,
        damage: 420,
        range: 160,
        fireRate: 0.9,
        damageType: DamageType.MAGIC,
        splashRadius: 100,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'void_shred_extreme',
            type: 'ARMOR_SHRED',
            value: 0.6,
            durationMs: 5000,
            remainingMs: 5000,
          },
        ],
        description: 'Tears open an astral vortex with massive 60% resistance destruction.',
      },
    },
  },

  [TowerType.CANNON]: {
    type: TowerType.CANNON,
    name: 'Heavy Cannon',
    description: 'Long-range siege mortar delivering massive kinetic shockwaves.',
    baseCost: 200,
    baseDamage: 90,
    baseRange: 180,
    baseFireRate: 0.4,
    damageType: DamageType.PHYSICAL,
    splashRadius: 64,
    chainCount: 0,
    chainDecay: 0,
    baseEffects: [],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Reinforced Howitzer',
        cost: 200,
        damage: 160,
        range: 200,
        fireRate: 0.45,
        damageType: DamageType.PHYSICAL,
        splashRadius: 72,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Upgraded barrel with heavier black powder payload.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'Cluster Mortar',
        cost: 350,
        damage: 280,
        range: 220,
        fireRate: 0.5,
        damageType: DamageType.PHYSICAL,
        splashRadius: 84,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Shell splits into secondary fragmentation bomblets on impact.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Siege Dreadnought',
        cost: 400,
        damage: 480,
        range: 280,
        fireRate: 0.3,
        damageType: DamageType.PHYSICAL,
        splashRadius: 96,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Super-heavy titan cannon designed to crush armored boss monsters.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Hellfire Battery',
        cost: 800,
        damage: 700,
        range: 250,
        fireRate: 0.65,
        damageType: DamageType.PHYSICAL,
        splashRadius: 110,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Continuous salvo of incendiary artillery shells.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Earthshaker Behemoth',
        cost: 850,
        damage: 1350,
        range: 320,
        fireRate: 0.35,
        damageType: DamageType.PHYSICAL,
        splashRadius: 130,
        chainCount: 0,
        chainDecay: 0,
        effects: [],
        description: 'Tectonic bombardment that shatters the strongest defenses.',
      },
    },
  },

  [TowerType.TESLA]: {
    type: TowerType.TESLA,
    name: 'Tesla Coil',
    description: 'Generates high-frequency lightning arcs that jump between multiple targets.',
    baseCost: 175,
    baseDamage: 35,
    baseRange: 130,
    baseFireRate: 1.0,
    damageType: DamageType.LIGHTNING,
    splashRadius: 0,
    chainCount: 4,
    chainDecay: 0.2, // 20% damage drop per jump
    baseEffects: [],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Capacitor Array',
        cost: 180,
        damage: 60,
        range: 145,
        fireRate: 1.2,
        damageType: DamageType.LIGHTNING,
        splashRadius: 0,
        chainCount: 5,
        chainDecay: 0.15,
        effects: [],
        description: 'Increases lightning chain count to 5 targets with less decay.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'High-Voltage Overdrive',
        cost: 320,
        damage: 130,
        range: 160,
        fireRate: 1.4,
        damageType: DamageType.LIGHTNING,
        splashRadius: 0,
        chainCount: 7,
        chainDecay: 0.1,
        effects: [
          {
            id: 'tesla_stun',
            type: 'STUN',
            value: 1.0,
            durationMs: 600,
            remainingMs: 600,
          },
        ],
        description: 'Electrifies targets, briefly stunning them with each shock.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Plasma Storm',
        cost: 340,
        damage: 110,
        range: 150,
        fireRate: 2.2,
        damageType: DamageType.LIGHTNING,
        splashRadius: 40,
        chainCount: 6,
        chainDecay: 0.12,
        effects: [],
        description: 'Superheats ionized gas creating secondary electrical splash.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Thor’s Megavolt',
        cost: 720,
        damage: 340,
        range: 180,
        fireRate: 1.8,
        damageType: DamageType.LIGHTNING,
        splashRadius: 0,
        chainCount: 10,
        chainDecay: 0.05,
        effects: [
          {
            id: 'megavolt_stun',
            type: 'STUN',
            value: 1.0,
            durationMs: 900,
            remainingMs: 900,
          },
        ],
        description: 'Unleashes 10-target chain lightning with devastating stun force.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Antimatter Discharge',
        cost: 760,
        damage: 290,
        range: 170,
        fireRate: 3.0,
        damageType: DamageType.LIGHTNING,
        splashRadius: 60,
        chainCount: 8,
        chainDecay: 0.08,
        effects: [],
        description: 'Rapid lightning barrage that obliterates grouped enemies.',
      },
    },
  },

  [TowerType.FROST]: {
    type: TowerType.FROST,
    name: 'Frost Obelisk',
    description: 'Chills enemies with glacial ice, slowing their movement speeds.',
    baseCost: 125,
    baseDamage: 15,
    baseRange: 125,
    baseFireRate: 1.2,
    damageType: DamageType.FROST,
    splashRadius: 36,
    chainCount: 0,
    chainDecay: 0,
    baseEffects: [
      {
        id: 'frost_slow_base',
        type: 'SLOW',
        value: 0.35, // 35% slow
        durationMs: 2500,
        remainingMs: 2500,
      },
    ],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Glacial Pillar',
        cost: 140,
        damage: 30,
        range: 140,
        fireRate: 1.4,
        damageType: DamageType.FROST,
        splashRadius: 48,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'frost_slow_tier2',
            type: 'SLOW',
            value: 0.45,
            durationMs: 3000,
            remainingMs: 3000,
          },
        ],
        description: 'Increases slow effect to 45% with expanded area of effect.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'Blizzard Core',
        cost: 260,
        damage: 65,
        range: 160,
        fireRate: 1.6,
        damageType: DamageType.FROST,
        splashRadius: 64,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'blizzard_slow',
            type: 'SLOW',
            value: 0.6,
            durationMs: 3500,
            remainingMs: 3500,
          },
        ],
        description: 'Freezes enemies to a crawl with intense 60% slow velocity decay.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Permafrost Spike',
        cost: 290,
        damage: 140,
        range: 150,
        fireRate: 1.1,
        damageType: DamageType.FROST,
        splashRadius: 40,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'deep_freeze',
            type: 'STUN',
            value: 1.0,
            durationMs: 1200,
            remainingMs: 1200,
          },
        ],
        description: 'Impales enemies with glacial shards that freeze them completely in place.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Zero-Kelvin Tempest',
        cost: 580,
        damage: 180,
        range: 190,
        fireRate: 2.0,
        damageType: DamageType.FROST,
        splashRadius: 90,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'absolute_zero_slow',
            type: 'SLOW',
            value: 0.75,
            durationMs: 4000,
            remainingMs: 4000,
          },
        ],
        description: 'Creates a massive sub-zero storm slowing enemy movement by 75%.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Cryo-Shatter Monolith',
        cost: 620,
        damage: 380,
        range: 175,
        fireRate: 1.4,
        damageType: DamageType.FROST,
        splashRadius: 60,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'cryo_perma_freeze',
            type: 'STUN',
            value: 1.0,
            durationMs: 2000,
            remainingMs: 2000,
          },
        ],
        description: 'Freezes targets solid for 2 full seconds with heavy shatter damage.',
      },
    },
  },

  [TowerType.BARRACKS]: {
    type: TowerType.BARRACKS,
    name: 'Command Bastion',
    description: 'Support fortress that inspires and enhances nearby friendly towers.',
    baseCost: 150,
    baseDamage: 0,
    baseRange: 150,
    baseFireRate: 0,
    damageType: DamageType.PHYSICAL,
    splashRadius: 0,
    chainCount: 0,
    chainDecay: 0,
    baseEffects: [
      {
        id: 'aura_speed_base',
        type: 'ATTACK_BUFF',
        value: 0.2, // +20% attack speed to neighbors
        durationMs: 1000,
        remainingMs: 1000,
      },
    ],
    upgrades: {
      tier2: {
        tier: 2,
        branchName: 'Warlord Citadel',
        cost: 160,
        damage: 0,
        range: 170,
        fireRate: 0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'aura_speed_tier2',
            type: 'ATTACK_BUFF',
            value: 0.3,
            durationMs: 1000,
            remainingMs: 1000,
          },
        ],
        description: 'Increases aura radius and grants +30% attack speed to adjacent towers.',
      },
      tier3BranchA: {
        tier: 3,
        branchName: 'High Marshall Spire',
        cost: 300,
        damage: 0,
        range: 190,
        fireRate: 0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'aura_speed_tier3',
            type: 'ATTACK_BUFF',
            value: 0.45,
            durationMs: 1000,
            remainingMs: 1000,
          },
        ],
        description: 'Grand command presence providing +45% attack speed aura.',
      },
      tier3BranchB: {
        tier: 3,
        branchName: 'Runic Armory',
        cost: 320,
        damage: 0,
        range: 180,
        fireRate: 0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'aura_damage_tier3',
            type: 'ATTACK_BUFF',
            value: 0.3,
            durationMs: 1000,
            remainingMs: 1000,
          },
        ],
        description: 'Imbues adjacent towers with runic energy increasing pure damage by 30%.',
      },
      tier4A: {
        tier: 4,
        branchName: 'Avatar of Valor',
        cost: 650,
        damage: 0,
        range: 220,
        fireRate: 0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'aura_haste_extreme',
            type: 'ATTACK_BUFF',
            value: 0.7,
            durationMs: 1000,
            remainingMs: 1000,
          },
        ],
        description: 'Radiates legendary frenzy haste: +70% attack speed to all towers in radius.',
      },
      tier4B: {
        tier: 4,
        branchName: 'Sanctum of Sovereignty',
        cost: 700,
        damage: 0,
        range: 200,
        fireRate: 0,
        damageType: DamageType.PHYSICAL,
        splashRadius: 0,
        chainCount: 0,
        chainDecay: 0,
        effects: [
          {
            id: 'aura_sovereign_might',
            type: 'ATTACK_BUFF',
            value: 0.5,
            durationMs: 1000,
            remainingMs: 1000,
          },
        ],
        description: 'Supreme fortress granting +50% bonus damage and range to allies.',
      },
    },
  },
};

export function calculateSellRefund(totalInvestedGold: number): number {
  return Math.floor(totalInvestedGold * 0.75); // 75% refund
}
